### ISSUE TITLE
Series flushed twice if error occurs

### ISSUE THREAD

**Issue by franzpoeschel** [openPMD/openPMD-api#1006]
When some error happens during `Series::flush()`, C++ will destroy all objects currently found on the stack, including the instance `Series`. `Series::~Series()` calls `Series::flush()`. Consequence: An error happening during `Series::flush()` will lead to `Series::flush()` being attempted a second time, on a broken object, often leading to completely different and mostly unrelated error messages.

This is annoying during development, I've often wasted time now looking into the wrong error that wasn't actually the problem. I imagine, having unrelated, seemingly random error messages is often not the best user experience either.

Suggestion: In `Series::flush`, catch any error, set a flag `unhandledError` or something. If that flag is found, the destructor does not call `Series::flush()`.

**Comment by ax3l** [comment]
Sounds reasonable, seems we need to treat `flush()` like a destructor...

**Comment by franzpoeschel** [comment]
> Sounds reasonable, seems we need to treat `flush()` like a destructor...

I don't think treating it as a destructor will work; often enough you don't want to destroy things yet when calling `flush()`. Suggestion for addressing this in #1018.
