### ISSUE TITLE
Wrong template specialization for `std::array`

### ISSUE THREAD

**Issue by eschnett** [openPMD/openPMD-api#1038]
**Describe the bug**

Lines 632 ff. of `Datatype.hpp` are:
```C++
    template<typename T, long n>
    struct BasicDatatypeHelper<std::array<T, n>> {
        Datatype m_dt = BasicDatatypeHelper<T>{}.m_dt;
    };
```

The intent is to determine whether a given type is an instance of `std::array<T,N>` or not. Unfortunately, the template for `std::array` is declared with a `std::size_t` length parameter (not `long`), and as a consequence, this specialization only matches when `std::size_t` is defined as `unsigned long` (macOS) and not when it is defined as `unsigned long long` (Linux). Thus the result of `basicDatatype` when called with `ARR_DBL_7` is either `DOUBLE` (macOS) or `ARR_DBL_7` (Linux).

**To Reproduce**
I don't have C++ code to reproduce this. I caught this in the self tests of the Julia wrapper.

**Expected behavior**
The function `basicDatatype` should return the same result on all operating systems and architectures.

To correct this, replace `long` with `std::size_t` in the template specialization. I corrected this in [this patch](https://github.com/eschnett/openPMD-api/commit/58391348d6efd8ce529dcc1548019904a63bcdd4) in the Julia bindings branch.

**Comment by ax3l** [comment]
Thanks, good catch!
Fix in #1040
