### ISSUE TITLE
Parallel: Offset Namings

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#11]
@C0nsultant namings parameters of offsets of MPI-ranks in parallel writes can be tricky.

Ideally, stick as close as possible to the openPMD namings in parameters.
If anything is missing, [here is how we call offsets in PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions) to fill the rest. (The old libSplash namings are outdated and inconsistent, don't read those please.)

**Comment by anokfireball** [comment]
I am not sure where in the code this would apply. The only place where the term ```Offset``` is used (but *not* enforced by openPMD) is the alias of ```std::vector``` used during dataset IO:

https://github.com/openPMD/openPMD-api/blob/b8e8de9187e7cc179589c974d042de9cf3ae92b4/include/openPMD/Dataset.hpp#L34

Across the whole codebase, that ```Offset``` is used to signal the offset in the overall dataset on persistent storage (i.e. the left edge of a chunk inside a dataset). It is always referred to simply as ```Offset offset``` or ```Offset o```.
No concepts from the parallel domain are incorporated at the moment. Every position (i.e. every ```Offset```) is treated as global.
