### ISSUE TITLE
openpmd-ls: Use defer_iteration_parsing ?

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#1110]
Should we use `defer_iteration_parsing` (#1109) in `openpmd-ls`?

Constructor: https://github.com/openPMD/openPMD-api/blob/0.14.2/include/openPMD/cli/ls.hpp#L99-L102

Executed logic: https://github.com/openPMD/openPMD-api/blob/0.14.2/src/helper/list_series.cpp#L39

**Comment by franzpoeschel** [comment]
Good idea
Only thing that might become difficult is if we want to expose to users the possibility to define their own JSON strings
I think it would be helpful later on to add something to our JSON header (and even reexport that to users) like:
```cpp
std::string mergeJsonConfigs( std::string const & defaults, std::string const & userDefines );
```

**Comment by franzpoeschel** [comment]
Also, not so important, but in this here:
```cpp
        try {
            auto s = Series(
                argv[1],
                Access::READ_ONLY
            );

            helper::listSeries(s, true, std::cout);
        }
        catch (std::exception const &e) {
            std::cerr << "An error occurred while opening the specified openPMD series!\n";
            std::cerr << e.what() << std::endl;
            return 2;
        }
```
A runtime_error might also be caught here that did not happen *while opening the series*, but while reading it in `listSeries`. Since `Series` is now default constructible, we could do sth like:
```cpp
Series s;
try { s = Series(...); } catch (...) { ... }
```
