### ISSUE TITLE
Gracefully handle unsupported compression in current ADIOS2 master

### ISSUE THREAD

**Issue by franzpoeschel** [openPMD/openPMD-api#1163]
**Describe the bug**
ADIOS2 generally throws an exception when adding an unsupported compression (e.g. adding Blosc compression when Blosc has not been compiled).
So far, we catch this exception and turn it into a warning. 

Something changed in the way ADIOS2 throws exceptions for these, so the openPMD-api currently does not catch them any more.

**Expected behavior**

Two options (we should discuss this before fixing anything):

1. Stick with the old behavior, i.e. fix the catching of the exception. This makes some CI workflows easier (which I think was the original reason I overrode the behavior of ADIOS2)
2. Change our behavior and adopt ADIOS2's behavior: Just forward the exception. This would mean that we have to fix some tests.

Opinion? @ax3l

**Comment by ax3l** [comment]
Glad you caught that (hah, pun intended).

As discussed today: We stick with 1. as this is pretty useful for complex deployments and does not harm but warn.
