### ISSUE TITLE
problem installing openPMD-API with pip

### ISSUE THREAD

**Issue by ppiot** [openPMD/openPMD-api#1176]
All, 
  After upgrading my computer (fc35) I was not able to install openPMD-api (but I was able to install openPMD-viewer just fine). 

**Performed steps**
The following steps were attempted

```
pip install openPMD-api
```
which returns  
ERROR: Could not find a version that satisfies the requirement openPMD-api (from versions: none)
ERROR: No matching distribution found for openPMD-api

**Comment by ax3l** [comment]
Hi @ppiot,

Thanks for raising this.

Can you try to update your `pip` [installation first](https://github.com/openPMD/openPMD-api#pypi)? It's often outdated on local distributions.

```bash
python3 -m pip install -U pip
python3 -m pip install openpmd-api
```

**Comment by ppiot** [comment]
Thank you, Axel. I had done these steps and retried. I can see the package from pip_search. But not able to install (I thought it was something messed up with my laptop and trued on another computer running fc35 and same problem). Though everything seems fine on our Centos7 clusters... 
![Screenshot from 2022-01-22 06-38-20](https://user-images.githubusercontent.com/71890013/150638829-ed5c6e15-73dc-4cf4-9f96-5f52ca4d4190.png)

**Comment by ax3l** [comment]
Hi,

Oh I see the problem: you were already using Python 3.10.

We just released openPMD-api 0.14.4, which adds Python 3.10 support. Can you try again in a few hours, when the pip packages are uploaded?

Best,
Axel

**Comment by ax3l** [comment]
Should work now :)

**Comment by ppiot** [comment]
@ax3l  all OK now! sorry for the confusion and thank you

**Comment by ax3l** [comment]
Oh, no worries. Thanks a lot for the report! Appreciate it :)
