### ISSUE TITLE
Decompression Parameters

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#1188]
The same way we can pass parameters when writing for operators/compression, we also need to expose parameters in reading.

This is needed to control the parallelism of compressors explicitly in ADIOS2 + c-blosc.

(Compressor algorithms themselves are of course handled automatically in reads by the file formats we implement.)

X-ref:
- https://github.com/ornladios/ADIOS2/pull/3014
- https://github.com/ornladios/ADIOS2/issues/3008

**Comment by guj** [comment]
Franz addressed this in PR #1191
