### ISSUE TITLE
ADIOS2 BP5 optimization: Allow users to "give up" their data into openPMD

### ISSUE THREAD

**Issue by franzpoeschel** [openPMD/openPMD-api#1216]
With BP5, using PerformPuts has a performance implication unlike in BP4 ([here](https://github.com/ornladios/ADIOS2/issues/2649#issuecomment-1057105950) is a detailed explanation). 

Users can currently avoid PerformPuts in two ways:

1. Use the span-based API
2. Use the streaming API and never flush()

A third way could theoretically be by allowing users to release their hold onto data:
```cpp
recordComponent.storeChunk( std::move( mySharedPointer ), offset, extent );
```

The ADIOS2 backend could then detect by using `std::shared_ptr::use_count()` that is the unique owner of the passed buffer and avoid calling PerformPuts().

**Big caveat:** This would be a breaking change since it would require openPMD to assume that the shared_ptr actually manages the memory. It would break things like this:
```cpp
std::vector<int> v{0,1,2,3,4,5};
recordComponent.storeChunk( std::shared_ptr<int>(v.data(), [](auto const * ptr){}), offset, extent);
```

This is not too bad because we already have an overload that takes vectors which most people use:
```cpp
std::vector<int> v{0,2,3,4,5};
recordComponent.storeChunk(v, offset, extent);
```
So we can use that overload for checking that situation.

A raw pointer overload should maybe be added for other cases.

**Comment by franzpoeschel** [comment]
Note: Even if we don't add this change, I suggest that we should add a raw pointer overload for `storeChunk()` so that we can stop promoting the antipattern of non-owning shared pointers.

**Comment by franzpoeschel** [comment]
Discussed yesterday in VC:

1. Neither PIConGPU nor WarpX would currently benefit from this since the Span API brings the same benefits and then some. We will for now not implement this optimization.
2. We will propagate a clear distinction between managed and non-managed memory in our storeChunk API to prepare for future optimization potential.

This means that we will prepare a PR that includes the following points:

1. Deprecate `shareRaw`
2. Add raw pointer overloads `storeChunkRaw` or similar. `storeChunkRaw(ptr,…)` will ultimately replace `storeChunk(shareRaw(ptr), …)`.
3. Document `storeChunk()` properly

**Comment by ax3l** [comment]
Implementation in #1294
