### ISSUE TITLE
0.15: Do not install toml

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#1217]
When doing the default super-build, the `toml` sub-project should not be installed.
It's a private dependency.

Follow-up to #1148 #1146.

Similar to:
- #556 / https://github.com/nlohmann/json/pull/1330
- https://stackoverflow.com/questions/35344132/cpack-exclude-install-commands-from-subdirectory-googletest-directory/51746390#51746390

**Comment by ax3l** [comment]
X-ref: https://github.com/ToruNiina/toml11/pull/185

**Comment by franzpoeschel** [comment]
> X-ref: [ToruNiina/toml11#185](https://github.com/ToruNiina/toml11/pull/185)

Should I close https://github.com/openPMD/openPMD-api/pull/1210/files then and we go with your solution as soon as it's merged?

**Comment by ax3l** [comment]
We can keep that PR open in case toml11 merges our PR too slowly (aka before we want to cut 0.15.0).

**Comment by ax3l** [comment]
Fixed via #1227
