### ISSUE TITLE
C++ code style & static code analysis in CI

### ISSUE THREAD

**Issue by anokfireball** [openPMD/openPMD-api#122]
It would be desirable to also have multiple checks for code quality, code style and static analysis of the code, independent of the compiler.

Possible code style checkers:
- [cpplint](https://github.com/google/styleguide/tree/gh-pages/cpplint) (Google)
- [KWStyle](https://github.com/Kitware/KWStyle) (KitWare)
- [vera++](https://bitbucket.org/verateam/vera/wiki/Introduction)
- ~[clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)~ #291

Possible code analysis tools:
- [OCLint](http://docs.oclint.org/en/stable/intro/tutorial.html)
- [Flint++](https://github.com/JossWhittle/FlintPlusPlus)
- ~[Clang-Tidy](https://clang.llvm.org/extra/clang-tidy/)~ #291
- [clang-analyzer](https://clang-analyzer.llvm.org/scan-build.html) / `scan-build`
- ~[include_what_you_use](https://include-what-you-use.org/)~ #291
- [Cppcheck](http://cppcheck.sourceforge.net/)
- [Codacy](https://www.codacy.com/) (post-commit hook for Github integration)
- [Coverity](https://scan.coverity.com/)

Test / Code coverage:
- [cppcoveralls](https://github.com/eddyxu/cpp-coveralls)
- ~[kcov](https://github.com/SimonKagstrom/kcov)~ #291

**Comment by ax3l** [comment]
Added [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) to the list.
Style questions related to https://github.com/ComputationalRadiationPhysics/contributing, so we can share them if we find something useful.

[ADIOS2](https://github.com/ornladios/ADIOS2/) has two example dotfiles in their repo for `clang-format` and `clang-tidy`.

**Comment by ax3l** [comment]
Added [clang-analyzer](https://clang-analyzer.llvm.org/scan-build.html) and [include_what_you_use](https://include-what-you-use.org/) to the 2nd list.

Here is a great resource on how to integrate common tools in modern CMake:
https://cliutils.gitlab.io/modern-cmake/chapters/features/utilities.html
