### ISSUE TITLE
Performance bug: Premature IO flushing when using scalar components

### ISSUE THREAD

**Issue by franzpoeschel** [openPMD/openPMD-api#1263]
See [this line](https://github.com/openPMD/openPMD-api/blob/e5bc793cd2a701bfb3258231629af85187d73b1b/src/Mesh.cpp#L233), similarly in `Record.cpp`.

In some backends, there are performance benefits from avoiding flushes before closing an iteration:

* BP4 engine of ADIOS2: The internal ADIOS2 buffer will be allocated to the correct size upon `Engine::EndStep()`. If flushing before that, it needs to be allocated before ending the step and might need to be resized later.
* BP5 engine of ADIOS2: Flushing in BP5 might cause unnecessary copies into internal buffers. If using deferred Put() and EndStep() only, BP5 can avoid copies entirely.

Calling `IOHandler()->flush()` at those place ruins this and should be replaced with something more fine-grained. 
It's currently essentially impossible to avoid these unnecessary copies into BP5 buffers while using scalar components.

**Comment by franzpoeschel** [comment]
There are other instances of premature flushing triggered by `Series::advance` that block usefulness of deferred mode.
I should do a PR that tries to eliminate them.

**Comment by ax3l** [comment]
Just to triage this properly: only in `dev` or also in `0.14.*`?

**Comment by franzpoeschel** [comment]
> Just to triage this properly: only in `dev` or also in `0.14.*`?

This also affects the release. Not high priority since for BP4 it's only an inconvenience (you can workaround this by specifying `InitialBufferSize`), but you cannot easily workaround the consequences of this for BP5
