### ISSUE TITLE
GCC 11.2 Warning About String in IOTask.cpp

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#1266]
GCC 11.2.0 on Perlmutter for the current `dev`:
```
/global/homes/a/ahuebl/src/openPMD-api/src/IO/IOTask.cpp: In static member function 'static void openPMD::Parameter<openPMD::Operation::CREATE_DATASET>::warnUnusedParameters(TracingJSON&, const string&, const string&) [with TracingJSON = openPMD::json::TracingJSON; std::string = std::__cxx11::basic_string<char>]':
/global/homes/a/ahuebl/src/openPMD-api/src/IO/IOTask.cpp:45:29: warning: loop variable 'key' of type 'const string&' {aka 'const std::__cxx11::basic_string<char>&'} binds to a temporary constructed from type 'const char* const' [-Wrange-loop-construct]
   45 |     for (std::string const &key : {"resizable"})
      |                             ^~~
/global/homes/a/ahuebl/src/openPMD-api/src/IO/IOTask.cpp:45:29: note: use non-reference type 'const string' {aka 'const std::__cxx11::basic_string<char>'} to make the copy explicit or 'const char* const&' to prevent copying
```

Is that a legit warning, I wonder?

**Comment by franzpoeschel** [comment]
> Is that a legit warning, I wonder?

I think it is. I think what currently happens is that in each iteration (well there only is one), a `std::string` is constructed on the fly from the `char const *` and then stored inside the const reference, extending its lifetime for the whole iteration.
It doesn't *look* like a copy is happening, so the compiler asks to rewrite it to the more obvious `for (std::string const key: {"resizable"})`, or to use the proper type to avoid copying `for (char const * key: {"resizable"})`.
