### ISSUE TITLE
Blosc Issue in 0.14.5 w/ ADIOS2

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#1293]
A user reported to me the following issue when upgrading openPMD-api 0.14.4 to 0.14.5 via the conda packages.

New read error for data we wrote a while ago with WarpX using openPMD-api and ADIOS2 v2.7.1:
> [Fri Jun 10 21:03:15 2022] [ADIOS2 EXCEPTION] <Operator> <CompressBlosc> <InverseOperate> : invalid blosc buffer version

Maybe three was a breaking change in ADIOS2 2.8.0/2.8.1 with regards to operators and/or blosc?

**Comment by psychocoderHPC** [comment]
The error is triggered here: https://github.com/ornladios/ADIOS2/blob/499d26865895f2a40367f09381a86de65557bd76/source/adios2/operator/compress/CompressBlosc.cpp#L248-L250
The error is triggered by a blosclz version change. See [here](https://github.com/ornladios/ADIOS2/blob/499d26865895f2a40367f09381a86de65557bd76/source/adios2/operator/compress/CompressBlosc.h#L100) for a short documenation of the blosc header bytes.

**Comment by psychocoderHPC** [comment]
The problematic line in ADIOS2 2.8.1 was introduced in https://github.com/ornladios/ADIOS2/pull/2932
I am not sure anymore if the blosc header is checked or if this version is an ADIOS internal version.

[update] It is an ADIOS internal version number. I do not know the meaning of the number.

**Comment by ax3l** [comment]
Oh, then that's a conda-forge issue where we already build agains the lastest ADIOS2. Need to fixate the version for 0.14.5

**Comment by ax3l** [comment]
dang that this is a breaking ADIOS 2.8 change in operators... to be discussed with @pnorbert next time :)

**Comment by ax3l** [comment]
I posted an upstream report in https://github.com/ornladios/ADIOS2/issues/3273

I try to temporarily hold back conda-forge builds (https://github.com/conda-forge/openpmd-api-feedstock/pull/89), but other targets such as ParaView superbuilds wil

**Comment by ax3l** [comment]
Fixed in ADIOS 2.8.3+.
Thanks a lot everyone for the quick turn-around and help! :sparkling_heart:

**Comment by ax3l** [comment]
@psychocoderHPC I cannot recall, were you able to test this fix? I am currently seeing a resurface of it with @n01r for ADIOS 2.8.3 and wonder if its truly fixed...

Data is written using ADIOS 2.7.1 and c-blosc v1.21.1, read uses ADIOS 2.8.3 and latest conda c-blosc 1.21.3.

**Comment by psychocoderHPC** [comment]
I thought the bug was fixed. Let me ping @steindev because he is more often running simulations with IO.

**Comment by steindev** [comment]
I cannot remember an instance of being not able to read data files within the last half year. However, I did not mix ADIOS2 versions between writing and reading. Anyway, thanks for the ping, I will keep an eye open.

**Comment by n01r** [comment]
Locally, I also don't seem to have a problem with my `mamba`-installed version of openpmd-api `0.14.5` and adios2 `2.8.3`.
I checked the exact same outputs, as @ax3l suggested.
Only on Perlmutter we seem to see this.
