### ISSUE TITLE
Includes in include/openPMD/openPMD.hpp have "openPMD/" prefix causing build error

### ISSUE THREAD

**Issue by matt-stack** [openPMD/openPMD-api#1306]
**What do you want to achieve, please describe.**

Hello, in include/openPMD openPMD.hpp, all the #includes are prefixed with "openPMD/*", but that file are already in that directory so I am getting a ton of 
No such file or directory                                                                                                                                                                    
   23 | #include "openPMD/config.hpp"                                                                                                                                                                       
      |          ^~~~~~~~~~~~~~~~~~~~   

/include/openPMD has both OpenPMD.hpp and config.hpp, but OpenPMD.hpp calls #include "openPMD/config.hpp"

Is this correct? Maybe I am doing something wrong..

It works when I take out the openPMD/ prefix

**Software Environment:**
Have you already installed openPMD-api? Yes

 - version of openPMD-api: latest-stack
 - installed openPMD-api via: spack

**Comment by franzpoeschel** [comment]
What exactly are you trying to do? Are you trying to compile openPMD-api or are you trying to include openPMD-api into another project? 

`#include` statements inside our source tree are all relative to `/include`, this is intentional. CMake sets the right compiler flags to properly resolve this part. Are you using CMake?

You can try following [these instructions](https://openpmd-api.readthedocs.io/en/0.14.5/install/install.html#from-source-with-cmake).

**Comment by ax3l** [comment]
Hi @matt-stack, are there any updates on this?

We use openPMD-api via Spack a lot. Spack sets the include path hints to  the `include/` dir in interplay with your build system (e.g., CMake). See the instructions here how to link to your project: https://github.com/openPMD/openPMD-api#linking-to-your-project

Note that you want to write
```C++
#include <openPMD/openPMD.hpp>
```
with the pointy `<...>` brackets.

**Comment by ax3l** [comment]
Hi @matt-stack, how is it going?

Can you provide a few more details how you compiled exactly (commands/Makefile/CMake logic) and apply the suggested changes? :)

**Comment by matt-stack** [comment]
Hello, I must have not set the includes paths, I had just built with cmake. I can close this, thank you for your help

**Comment by ax3l** [comment]
Thanks for the update, glad this works for you!

Please don't hesitate to reach out if you encounter any other issues :)
