### ISSUE TITLE
CMake fails to find parallel HDF5 when openPMD is used downstream

### ISSUE THREAD

**Issue by bernhardmgruber** [openPMD/openPMD-api#1339]
**Describe the bug**
openPMD looks for a parallel HDF5 during configure time, but for the normal one when used downstream.

**To Reproduce**
Clone openPMD-api on Ubuntu 22.10 (probably others work as well).
`sudo apt install libhdf5-mpi-dev`
Configure (with  just the shared library, no examples, tests and CLI), build and install openPMD.
HDF5 is found during configure:
```
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;/usr/lib/x86_64-linux-gnu/libcurl.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.a;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.8") found components: C
```

CMake-configure a downstream project (like picongpu) using openPMD. The configuration fails with:
```
-- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
-- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found version "")
CMake Warning at CMakeLists.txt:319 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/openPMD/openPMDConfig.cmake

  but it set openPMD_FOUND to FALSE so package "openPMD" is considered to be
  NOT FOUND.  Reason given by package:

  openPMD could not be found because dependency HDF5 could not be found.



-- Could NOT find openPMD - set openPMD_DIR or check your CMAKE_PREFIX_PATH
```

**Expected behavior**
The downstream configure would succeed.

**Software Environment**
 - version of openPMD-api: 0.14.5 or dev
 - installed openPMD-api via: from source
 - operating system: Ubuntu 22.10 inside WSL
 - machine: personal notebook
 - name and version of Python implementation: [e.g. CPython 3.9]
 - version of HDF5: 1.10.8
 - version of ADIOS1: none
 - version of ADIOS2: none
 - name and version of MPI: OpenMPI 4.1.4

The problem is likely the missing `set(HDF5_PREFER_PARALLEL ON)` in `openPMDConfig.cmake.in`, which is present in `CMakeLists.txt`. At least, adding it resolves the problem.

**Comment by ax3l** [comment]
cc @s-sajid-ali might be relevant for your install, too. Fix is coming via #1340
