### ISSUE TITLE
Build fails with the latest glibc. Catch2 module version too old.

### ISSUE THREAD

**Issue by khou2020** [openPMD/openPMD-api#1342]
**Describe the bug**
OpenPMD uses an older version of the external module Catch2 that is incompatible with the latest glibc version.
See https://github.com/catchorg/Catch2/issues/2421

**To Reproduce**
wget https://github.com/openPMD/openPMD-api/archive/refs/tags/0.14.5.tar.gz
tar -zxf openPMD-api.tar.gz
cd openPMD-api
mkdir build
cd build
cmake \
-DopenPMD_USE_MPI=ON \
-DopenPMD_USE_ADIOS2=OFF \
-DopenPMD_USE_HDF5=ON \
-DopenPMD_USE_ADIOS1=OFF \
-DopenPMD_USE_PYTHON=OFF \
-DCMAKE_CXX_STANDARD=14 \
-DCMAKE_PREFIX_PATH=openpmd_install_path \
..
make -j 4

**Expected behavior**
Library builds without problem.

**Software Environment**
 - version of openPMD-api: 0.14.5
 - installed openPMD-api via: from source
 - operating system: Ubuntu 22.04
 - machine: git action
 - name and version of Python implementation: n/a
 - version of HDF5: 1.13.2
 - version of ADIOS1: n/a
 - version of ADIOS2: n/a
 - name and version of MPI: mpich 4.0.2

**Additional context**

**Comment by ax3l** [comment]
Thank you for the report @khou2020 !

Are you sure it's that catch issue? According to the maintainer, 2.13.5+ should fix it and we already ship 2.13.9+:
https://github.com/catchorg/Catch2/issues/2421#issuecomment-1121307652

**Comment by ax3l** [comment]
Ah right, our 0.14.5 release still ships Catch2 v 2.13.4 which is affected:
https://github.com/openPMD/openPMD-api/tree/0.14.5#dependencies

So `dev` does fix the issue for you, right? :)

X-ref:
- #1299
- #1344

**Comment by khou2020** [comment]
The current dev branch (1774623c84304a388230f08e1374141992d1adbf) works.
