### ISSUE TITLE
Python: `len(series)`

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#1375]
We should consider if we want to overwrite the `__len__`/`len()` of `openPMD_api.Series`.

Currently, it (probably) returns the number of attributes as for all Attributable objects in openPMD.

It might be maybe a bit more intuitive if it returns the `len(series.iterations)` instead.

First seen by @RTSandberg .

Refs.:
- https://docs.python.org/3/library/functions.html#len

**Comment by franzpoeschel** [comment]
We should generally do an overhaul of our object model in Python. The string representations of many classes are counterintuitive and have led to confusion, e.g. `series.iterations` printed will look as if it is empty:

```
> s.iterations
<openPMD.Attributable with '0' attributes>
>>> s.iterations[0]
<openPMD.Iteration at t = '0.000000e+00 s'>
```

Also, now that we have done a redesign of our C++ object model, we can introduce proper semantics for equality comparison. I recently wanted to use record components as keys in a Python dict, this currently leads to crashes. --> #1658
