### ISSUE TITLE
Determining scalar valued mesh and vector valued mesh

### ISSUE THREAD

**Issue by kimjohn1** [openPMD/openPMD-api#1376]
I am a novice with openPMD.  I have an application that runs a PIConGPU simulation and uses openPMD SST to pass data generated by the simulation to a visualization application that visualizes the data as the simulation runs.  All that is working great, and primarily made possible by openPMD SST.  Nice work there.
As the simulation begins and the first set of data is read, I have the Reader print what data is present, using code something like this:
``` 
if(iteration.particles.size())
{print particle data to the terminal}
else {print a message that there is no particle data in the data set}

if(iteration.meshes.size())
{print mesh data to the terminal}
else {print a message that there is no mesh data in the data set}
```
I would like to divide the presentation of mesh data into scalar valued mesh data and vector valued mesh data, but I don't see a simple way to make that distinction.  In the one simulation that I have been using, there are ```E``` and ```B``` vector valued meshes and ```e_all_chargeDensity``` and ```e_all_energyDensity``` scalar valued meshes, but I have not found a variable name or other simple way to separately determine presence of vector valued mesh data and presence of scalar valued mesh data.
I realize I could define ```MeshRecordComponent``` for each of these meshes and then ```getExtent()``` for each of them and use a compound ```if``` statement to get the job done, but that seems clumsy.  Let me know if there is a simpler way.
Thanks,
Kim

**Comment by franzpoeschel** [comment]
Hello Kim,
this should be possible to determine by calling something like `iteration.meshes["E"].scalar()` or `iteration.particles["e"]["position"].scalar()`. Is this what you are looking for?

> openPMD SST

Small note: SST is an engine of [ADIOS2](https://github.com/ornladios/ADIOS2), the part of openPMD is that it implements an ADIOS2 backend.

**Comment by kimjohn1** [comment]
@franzpoeschel 
Excellent.  I gave it a try and found that I need to determine that particle or mesh data is present first, something like this
```
if(iteration.particles.size())
    {
    if(iteration.particles["e"]["position"].scalar()) e_particlesPresent = true;
    .
    .
    .
    }
if(iteration.meshes.size())
    {
    if(iteration.meshes["E"].scalar()) E_vectorFieldPresent = true;
    .
    .
    .
    }

```

Looks like that will do it.  I need to make this determination for every particle and mesh.  Is there a list of particle and mesh types in the documentation somewhere?
Writing in plain text, would it be appropriate to say something like this?
> My project uses the 'data queue' concept implemented in openPMD ADIOS2 SST to synchronize execution of simulation and visualization applications.

Or should I leave openPMD out of there?

Thanks again,
Kim

**Comment by franzpoeschel** [comment]
> Writing in plain text, would it be appropriate to say something like this?
> 
> > My project uses the 'data queue' concept implemented in openPMD ADIOS2 SST to synchronize execution of simulation and visualization applications.
> 
> Or should I leave openPMD out of there?

I'd say that mentioning all involved software is going to be the best part. 
Maybe something like `…uses the SST engine of ADIOS2 for streaming I/O via the openPMD-api to synchronize…`

Graphic 3 from [this paper](https://arxiv.org/pdf/2107.06108.pdf) might be helpful as an overview
![grafik](https://user-images.githubusercontent.com/14241876/221226245-9af7aba8-ffc9-43c9-abaa-5352528c123f.png)

**Comment by kimjohn1** [comment]
@franzpoeschel 
Interestingly, I had referenced figure 2 from the paper in my documentation.  I'll swap figure 3 for that and tidy up the text as well.
I believe my original issue is answered.  I'm closing the issue with this comment.  Thanks.
