### ISSUE TITLE
Issue with the 2_read_serial.py example

### ISSUE THREAD

**Issue by max-lehman14** [openPMD/openPMD-api#1377]
I followed the example 2_read_serial.py (https://github.com/openPMD/openPMD-api/blob/dev/examples/2_read_serial.py) and got the following Error:

**AttributeError: 'openpmd_api.openpmd_api_cxx.Series' object has no attribute 'close'**

**Comment by franzpoeschel** [comment]
You are using an example from the dev branch, that uses a new API call `Series.close()`. I assume that you installed the latest release, in this case please try this link: https://github.com/openPMD/openPMD-api/blob/0.14.5/examples/2_read_serial.py

**Comment by max-lehman14** [comment]
This has fixed it.
Thank you
