### ISSUE TITLE
Reference Return is Dangerous

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#144]
From the first `1_structure.cpp` example:
```C++
// ...
ParticleSpecies &electrons = series.iterations[1].particles["electrons"];

Record          &mass        = electrons["mass"];
RecordComponent &mass_scalar = electrons["mass"][RecordComponent::SCALAR];
// ...
```

Such constructs can be quite dangerous if users forget the `&`. Are for all those objects the
- copy constructors
- assignment operators
- move constructors?

properly protected?

Otherwise users will copy objects and operate on them without ever modifying the actual ones they aimed for.

Possible, verbose alternative: some kind of handles as wrappers.

cc @psychocoderHPC

**Comment by anokfireball** [comment]
This has been in the back of my mind during the whole devlopement.
The main influence for this behaviour was interface design without consideration for implementation.

Your fear is correct - the obejcts are detatched during copies and only reattached when reassigned.
My proposal is to keep the current interface and implement what you call handles. Each ```Writable``` would then be a wrapper and contain a reference/pointer to a concrete object.

One could then discuss whether the object implements openPMD logic where the wrapper just delegates to the object. 
```c++
class SeriesImpl : public Attributable
{
public:
  /* ... */

  std::string openPMD() const;
  void setBasePath(std::string const& bp);
  /* ... */
}  // SeriesImpl

class Series
{
public:
  static Series create(/* ... */);
  static Series read(/* ... */);

  std::string openPMD() const;
  Series& setBasePath(std::string const& bp);
  /* ... */
private:
  std::shared_ptr< SeriesImpl > m_object;
}  // Series
```

```c++
void
SeriesImpl::setBasePath(std::string const& bp)
{
  std::string version = openPMD();
  if( version == "1.0.0" || version == "1.0.1" || version == "1.1.0" )
    throw std::runtime_error("Custom basePath not allowed in openPMD <=1.1.0");

  setAttribute("basePath", bp);
}

Series&
Series::setBasePath(std::string const& bp)
{
  m_object->setBasePath(bp);
  return *this;
}
```

Alternatively, the object can be the bare minimum Attributable and the wrapper contains the openPMD logic.

```c++
class Series
{
public:
  static Series create(/* ... */);
  static Series read(/* ... */);

  std::string openPMD() const;
  Series& setBasePath(std::string const& bp);
  /* ... */
private:
  std::shared_ptr< Attributable > m_object;
}  // Series
```

```c++
Series&
Series::setBasePath(std::string const& bp)
{
  std::string version = openPMD();
  if( version == "1.0.0" || version == "1.0.1" || version == "1.1.0" )
    throw std::runtime_error("Custom basePath not allowed in openPMD <=1.1.0");

  m_object->setAttribute("basePath", bp);
  return *this;
}
```

In both cases moving, copying and assigning would not detatch the objects. The references/pointers of the copies would then simply point to the exisiting objects.

Continuing from this, one should offer a ```Series Series::deepCopy()``` option if a detatched copy is desired.

This should handle #143 as well.

**Comment by ax3l** [comment]
@C0nsultant can you do this issue next please? Together with #143 this is a bit of a blocker for finishing the python bindings #32

**Comment by anokfireball** [comment]
Will be working on it in the next few days.
As a sidenote, this will not require a change to every class that derives from ```Attributable```. We can limit this change to ```Attributable``` itself with a moderate amount of code modification in the backend. The frontend will likely remain untouched (move constructors and assignment operators can be deleted in the base class ```Attributable```).
