### ISSUE TITLE
release 0.15.1 wrong patchlevel in version.hpp

### ISSUE THREAD

**Issue by psychocoderHPC** [openPMD/openPMD-api#1454]
For the release 0.15.1 the value for `OPENPMDAPI_VERSION_PATCH` was not updated and is therefore reporting the wrong patch level.

https://github.com/openPMD/openPMD-api/blob/32cb87d1b0012493287204d7a8c78af9a1141710/include/openPMD/version.hpp#L32

**Comment by s-sajid-ali** [comment]
This was fixed in spack: https://github.com/spack/spack/pull/36662

**Comment by ax3l** [comment]
Thank you for the report. We are already aware of this, fixed it in pkgs managers and will fix it in 0.15.2.

We also work on an update script to avoid this in the future: #1467

**Comment by ax3l** [comment]
Will be fixed in #1507 for 0.15.2

Patch for 0.15.1: https://github.com/openPMD/openPMD-api/pull/1414#issuecomment-1497787590
