### ISSUE TITLE
Unclear error message for unsupported file format

### ISSUE THREAD

**Issue by eschnett** [openPMD/openPMD-api#1471]
I tried to write a JSON-formatted file with openPMD_api 0.15.1. I received the error message `Unknown file format! Did you specify a file ending?`.

It would be nice if the error message included the file name and the suffix that openPMD doesn't understand.

**Comment by ax3l** [comment]
Thank you for the report and @franzpoeschel for the fix.

This will be part of the 0.15.2 release.
