### ISSUE TITLE
Passing of advanced backend parameters

### ISSUE THREAD

**Issue by anokfireball** [openPMD/openPMD-api#150]
An option to provide advanced parameters specific to a backend is desirable. This can include MPI_Info, file access strategies,communication strategies, buffer sizes among other things. This should be *optional* with sane defaults for all values.

Specifically, this matters in two places:
 - Series, where one would provide general backend parameters shared across all files, paths, datasets and attributes in the Series (e.g. MPI_Info, ADIOS_AGGREGATE, nometa)
```cpp
namespace openPMD
{
Series::Series(std::string const& filepath,
              AccessType at,
              MPI_Comm comm,
              AbstractSeriesParam* = nullptr /* default */);
} // openPMD
```
 - Datasets, where one would provide parameters different for specific datasets (e.g. compression/transform)
```cpp
namespace openPMD
{
Dataset&
Dataset::setParameters(AbstractDatasetParam*);
} // openPMD
```

Implementation can be done via polymorphic parameter structs (similar to ```IO::Parameter```) where paramters are passed named and typesafe (preferred) or as a map (similar to ```backend::Attributable```) (not preferred).

**Comment by ax3l** [comment]
I would suggest to pass an object by value for `AbstractSeriesParam`. One can still add a default dummy as default arg:
```C++
Series::Series(std::string const& filepath,
              AccessType at,
              MPI_Comm comm,
              AbstractSeriesParam = SeriesDefaultParam{});
```

We can also add a `Series::setOptions()` method for later adjustment, but some flags might already be needed at construction time.

**Comment by franzpoeschel** [comment]
To get back on this, a further option could be using JSON. We already ship with [Niels Lohmann's JSON library](https://github.com/nlohmann/json). This would allow to flexibly express backend-specific configuration options while at the same time not requiring to implement backend-specific classes like the solution with `AbstractSeriesParam`.

As an example, choosing the ADIOS2 engine with a JSON configuration:
```json
{
  "Engine": {
    "Type": "SST",
    "Params": {
      "QueueLimit": 3,
      "QueueFullPolicy": "Block"
    }
  }
}
```
This can be easily exposed to the Python API by passing the JSON configuration [as a simple string](https://github.com/nlohmann/json#tofrom-strings).

**Comment by ax3l** [comment]
Regarding HDF5 options and #554 : we can also try to expose [`H5FD_MPIO_INDEPENDENT`](https://support.hdfgroup.org/HDF5/doc/RM/H5P/H5Pset_dxpl_mpio.htm) again as @RemiLehe just mentioned offline. We did this in the past in [libSplash](https://github.com/ComputationalRadiationPhysics/libSplash/blob/v1.7.0/src/include/splash/core/DCParallelDataSet.hpp) but had no success with it, e.g. deadlocks or very bad parallel performance. We can see if MPI-IO implementations improved by just exposing it.

**Comment by franzpoeschel** [comment]
I have started work on backend-specific configuration options, using [Niels Lohmann's JSON library](https://github.com/nlohmann/json) (which is already in usage for the openPMD API's JSON backend).
I will publish and link this after cleaning things up for a bit.

**Comment by ax3l** [comment]
Thanks, just ping us on a WIP PR? :)

Another thing I want to add as an option: in case we build with ADIOS1 and ADIOS2 support, it would be great to choose the backend priority at runtime (for e.g. benchmarks) instead of having to re-compile.
