### ISSUE TITLE
series.flush(): selected Dataset?

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#155]
From the current discussion in the ADIOS2 "Perform()" API: Should we allow passing optional `Dataset`s to the `Series::flush()` member for selective flushing?

(No arguments by default: flush all.)

**Comment by anokfireball** [comment]
Again, this has similar implications to #91:

All IO operations - whether explicitly stated by the user or implicitly required for openPMD consistency - are appened to a linear, sequential queue. What you are proposing here goes beyond this sequence.

This could be achieved, but will require significant effort for a simple reason: Currently, there is no guarantee at any point that a IO operation can succeed in isolation - it might depend on **ALL** other, previously scheduled and possibly executed operations. This was trivially easy to implement as a queue with the added catch that the frontend logic has to schedule all operations with this constraint in mind.

Should you now really want to hand this control over to the user, a non-trivial change in the backend will be required: We will have to build a dependency graph that describes the scheduled, but not yet executed IO operations. To then "selectively flush", one would have to compute the minimum subgraph that adheres to the previous constraint, but is limited to the desired ```Dataset```.

**Comment by ax3l** [comment]
Thanks for the details, I am starting to get a deeper grasp on the IO task queue #153 :)

It's really just a question to understand the implications and constrains of the IO queue, I don't think it's urgently needed feature to selectively flush since one can as a user just simply write temporary data first as a "work-around".
