### ISSUE TITLE
Series: Open with Placeholder for File-Ending/Backend

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#1561]
I realized that in many situations, generalized post-processing scripts, CI, etc., it would be cool if we could open a series of the kind
```C++
auto s = openPMD::Series("samples/git-sample/data%T.*", openPMD::Access::READ_ONLY);
```
or
```C++
auto s = openPMD::Series("samples/git-sample/data%T.%B", openPMD::Access::READ_ONLY);
```

without having to specify the backend. The logic would just match the first backend that fits the pattern.

In openPMD-viewer, we approach this by just specifying the directory in which files are placed, which has the downside that there cannot be multiple series in the same directory.

What do you think, @franzpoeschel ? :)

**Comment by franzpoeschel** [comment]
This recently came up also in PIConGPU where it's annoying in post-processing scripts to pass the used extension, CC @PrometheusPi.
Implementation-wise I'd say this is doable, but can become finnicky in the details.
Would this also work?
```cpp
auto s = openPMD::Series("samples/git-sample/data%T.%E", openPMD::Access::READ_ONLY);
```
`%E` for extension is probably a bit clearer, no?
