### ISSUE TITLE
Container: Read Only Access

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#160]
The `openPMD::Container::operator[]` creates keys if they are missing on first access.

This is probably not ideal when a `Series` is opened as `READ_ONLY` on which access to missing
- iterations
- records
- record components

should probably throw a clean key error.

Any idea if we should and if yes how we could implement this (for the user-facing parts)?

**Comment by anokfireball** [comment]
Very good observation! Currently, this would only be noticable when the user triggers [any](https://github.com/openPMD/openPMD-api/blob/dev/src/IO/HDF5/HDF5IOHandler.cpp#L97) operations modifying data on disk.

As the ```accessType``` can not be changed after the ```Series``` has been created, the system is in a faulty state as soon as the access succeeds. We should probably fail fast_er_ when we discover this. 

If we fail fast, it should be done at ```openPMD::Container::operator[]``` level: Every ```Container``` has an ```IOHandler``` with known ```accessType```, so the check can happen as a precondition. If that state is reached, the system was brought into an unrecoverable state by the user and we should abort.

**Comment by ax3l** [comment]
Thanks for the hint, I suggested a solution in #172

**Comment by ax3l** [comment]
We implemented it! :)
