### ISSUE TITLE
Flush required for temporary vector attributes?

### ISSUE THREAD

**Issue by pgrete** [openPMD/openPMD-api#1603]
I'm trying to store some data (of multiple objects) similar to
```C++
for (obj : objects) {
  std::vector<double> tmp = GetStdVector(obj);
  iteration.setAttribute(obj.label(), tmp);
}
```
Is this safe (i.e., is the content of the temporary vector persistent in the openpmd-api internals) or do I need to make sure that the memory still lives until I call flush?

**Software Environment:**
Have you already installed openPMD-api?
If so, please tell us which *version* of openPMD-api your question is about:

 - version of openPMD-api: [1.15.2]
 - installed openPMD-api via: [conda-forge, spack, pip, brew, yggdrasil, from source, module system, ...]

**Comment by franzpoeschel** [comment]
> Is this safe (i.e., is the content of the temporary vector persistent in the openpmd-api internals) or do I need to make sure that the memory still lives until I call flush?

Yes, this is safe. The operation will generally be passed on to the I/O backend later upon `flush()`ing only, but attributes don't keep handles on user data, they are stored internally.

Note also that `setAttribute` uses pass-by-value, so the function header alone gives us no chance to access the user vector:
```cpp
template <typename T>
inline bool Attributable::setAttribute(std::string const &key, T value)
```

**Comment by pgrete** [comment]
Perfect, thanks for confirming.
