### ISSUE TITLE
MSVC: get<long double> bad_variant_access

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#179]
Currently the following test fails with MSVC 19 (VS 14, 2015), probably due to it's `double` == `long double` implementation:

```
3: C:\projects\openpmd-api\test\SerialIOTest.cpp(845): FAILED:
3:   REQUIRE( s.getAttribute("longdouble").get< long double >() == 1.e80L )
3: due to unexpected exception with message:
3:   bad_variant_access
3: 
3: Datatype::UNDEFINED caught during dataset creation (serial HDF5)
3: ===============================================================================
3: test cases:  13 |  12 passed | 1 failed
3: assertions: 213 | 212 passed | 1 failed
3: 
 3/10 Test  #3: Serial.SerialIO ..................***Failed    0.41 sec
test 4
      Start  4: Serial.1_structure
```

Example in https://ci.appveyor.com/project/ax3l/openpmd-api/build/1.0.140/job/jo3nh9xgb03poikp

I think we should be able to emulate that behavior with gcc with the `-mlong-double-64` switch (but from a first test this does not trigger it).

**Comment by ax3l** [comment]
@C0nsultant do you have an idea what could be causing this? I can also for now just quickly disable the `long double` reads on MSVC and we fix it after #63 is in.

**Comment by anokfireball** [comment]
Sorry, no obvious reason comes to mind. I would first check what the actual datatype that gets stored is:

```cpp
#include <iostream>

#include <openPMD/backend/Attribute.hpp>
#include <openPMD/Datatype.hpp>

int main()
{
  long double ld = 0.;
  Attribute a(ld);
  std::cout << "Determined datatype: " << determineDatatype< long double >() << '\n'
            << "Stored datatype:     " << a.dtype << std::endl;
  return 0;
}
```

Depending on what this results in, we might have to disable ```long double``` conditionally.

**Comment by ax3l** [comment]
I pushed a demonstrator in #184
