### ISSUE TITLE
Created Examples Do Not Pass Validator

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#187]
I just realized the created example files such as
- `1_structure.h5`
- `3_write_serial.h5`
- `5_parallel_write.h5`

do not pass the [validator](https://github.com/openPMD/openPMD-validator/).

We are probably just missing a few attributes from what I see so far, e.g. `geometry`.

**Comment by anokfireball** [comment]
It would be very nice to have this as a default step in our CI pipeline, sort of like an integration test to see whether the API plays nicely with the outside world or just fools itself by interpreting doubly incorrect results as good.

**Comment by ax3l** [comment]
Yes, probably in a later step. I try not to "pollute" the install with too much other packages like `h5py` until everything is installed. Probably we need to move the travis `script` section to `before_script` and then add such additional software and tests in `script` ([because later sections are not causing a build to fail](https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build))
