### ISSUE TITLE
std::complex

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#203]
Although not part of the openPMD standard yet, handling of types for [`std::complex< T >`](https://en.cppreference.com/w/cpp/numeric/complex) with `float`, `double` and `long double` could be investigated.

Keep in mind:
- be compatible with `h5py`: http://docs.h5py.org/en/latest/faq.html
- ADIOS1 support
- ADIOS2 support
- openPMD-standard issues: https://github.com/openPMD/openPMD-standard/issues/29 https://github.com/openPMD/openPMD-standard/issues/144

**Comment by CFGrote** [comment]
yep, i need this for wavefront data. any progress here?

**Comment by ax3l** [comment]
We haven't started working on this yet. I defend in a week from now, little time to look into this right now but maybe you can store it interleaved like we do it for the thetaMode geometry?

Of course, thoughts and PRs are welcome as well :)

**Comment by CFGrote** [comment]
ok, interleaving should work. good luck for next week!

**Comment by ax3l** [comment]
For the interested reader of this issue that would like to work on this:
the first step is to define new data types in [`include/openPMD/Datatype.hpp`](https://github.com/openPMD/openPMD-api/blob/dev/include/openPMD/Datatype.hpp)

Then, e.g. starting with HDF5, one defines new types in the backends such as [`src/IO/HDF5/HDF5IOHandler.cpp`](https://github.com/openPMD/openPMD-api/blob/dev/src/IO/HDF5/HDF5IOHandler.cpp). For HDF5 in particular, we want to be compatible with [h5py](https://github.com/h5py/h5py)'s representation of types [[1]](http://docs.h5py.org/en/stable/config.html) [[2]](http://docs.h5py.org/en/stable/faq.html) ([more general info on compound types](https://support.hdfgroup.org/HDF5/doc1.6/UG/11_Datatypes.html)).

In ADIOS1 (https://github.com/ornladios/ADIOS/search?q=complex&unscoped_q=complex) as well as ADIOS2, complex data types are supported by default: https://adios2.readthedocs.io/en/latest/components/components.html#variables-data-types

In JSON we probably just write a `real-imaginary` tuple.

**Comment by ax3l** [comment]
Implementation started in #639

**Comment by ax3l** [comment]
The implementation is mainly done, just waiting for a new ADIOS2 release to be tagged. We contributed support for complex types in attributes: https://github.com/ornladios/ADIOS2/issues/1908

**Comment by ax3l** [comment]
Standardization agreed upon and documented here: https://github.com/openPMD/openPMD-standard/issues/29#issuecomment-685903555

#639 adds the implementation in the API and will be shipped with the next release, openPMD-api 0.12.0.
