### ISSUE TITLE
minimum version requirement of HDF5

### ISSUE THREAD

**Issue by qiminglu** [openPMD/openPMD-api#213]
The document says that it needs the 1.8.6+ version of HDF5. However in HDF5IOHandler.cpp it has called the H5free_memory() method which is only available from HDF5 1.8.13+, please see the following link

https://support.hdfgroup.org/HDF5/doc/RM/RM_H5.html#Library-FreeMemory

With HDF5 v1.8.13 it compiles and the examples run fine for me.  So maybe should update the document for the minimum HDF5 version requirements.

**Comment by anokfireball** [comment]
Thank you very much for this report, @qiminglu!
This is a prime example of what an issue should contain - a clear description, a reason for the behaviour and even a tested fix.

@ax3l do you think we should consider adding one CI step that builds with the minimal required dependency versions so we catch this by ourself in the future?

**Comment by ax3l** [comment]
@qiminglu thank you for the report! :sparkles: 

@C0nsultant no CI needed for that, we just bump the version inf`find_package()` in CMake and the docs accordingly. Or do you mean we should build the *oldest supported* HDF5 version in CI? Good idea!

**Comment by anokfireball** [comment]
>  Or do you mean we should build the oldest supported HDF5 version in CI?

Yeah, that's where I was going. Currently, we just pull the default versions of [HDF5](https://github.com/openPMD/openPMD-api/blob/15cda606d55ecc9d3748000182a56babbc21a0ea/.travis.yml#L279) and [ADIOS](https://github.com/openPMD/openPMD-api/blob/15cda606d55ecc9d3748000182a56babbc21a0ea/.travis.yml#L286).
Maybe we should have one build in travis that builds against the minimum requirements (i.e. oldest supported version).

**Comment by ax3l** [comment]
Added in #215 for HDF5.
