### ISSUE TITLE
Avoid <regex> (for now)

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#216]
As discussed in #210, we will try to also support GCC 4.8.

For this to work, the only thing we will need to change is the use of `<regex>` inside the library, as it is only implemented as a stub in GCC 4.8.

Possible alternatives are:
- own, simple string matcher for file names
- use another light-weight regex library, e.g. [slre](https://github.com/cesanta/slre)

For reference, [this](https://github.com/openPMD/openPMD-api/pull/217#issuecomment-393532139) is what needs to be solved.

**Comment by ax3l** [comment]
@C0nsultant if you have an idea how to implement this efficiently, feel free to say how or go ahead. I just tried to quickly hack it but needs more thinking.

**Comment by anokfireball** [comment]
You weren't far off. The only thing you didn't consider are the troubles caused by having both a prefix and a postfix.
I'll look into it.

**Comment by ax3l** [comment]
Since it's a GCC 4.8 only issue, we could also use the POSIX [`<regex.h>` header](http://man7.org/linux/man-pages/man3/regex.3.html) or the [regex lib](https://developer.gnome.org/glib/stable/glib-Perl-compatible-regular-expressions.html) from `glibc` here as a fallback.

Resources:
- https://stackoverflow.com/questions/31628536/what-is-difference-between-c-and-c-regex
- http://lh3lh3.users.sourceforge.net/reb.shtml

**Comment by ax3l** [comment]
Ok, I have a new draft based on the POSIX C `<regex.h>`
