### ISSUE TITLE
Gitter chat room

### ISSUE THREAD

**Issue by anokfireball** [openPMD/openPMD-api#276]
Maybe it would be benefitial to a have a chat room at [gitter](https://gitter.im/) tied to this repo.

This way, we could have a central place for inquiries and discussions that do are not big enough for an issue yet.

This would require changing the OAuth settings of the openPMD organization. See gitter [docs](https://gitlab.com/gitlab-org/gitter/webapp/blob/develop/docs/faq.md#why-isnt-my-github-organisation-or-repos-appearing).

**Comment by ax3l** [comment]
We actually have a gitter for general openPMD already reserved :)
https://gitter.im/openPMD

Just... have... to.. find.. option... to open.. for.. non-members... as... well.. argh...

Hm, new channel: https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-communities-and-rooms

Here we go:
  Lobby https://gitter.im/openPMD/Lobby

Of course we can add more, e.g. dedicated to the API.

**Comment by anokfireball** [comment]
[Let's all go to the lobby!](https://www.youtube.com/watch?v=hjB5gjTEEj8)

**Comment by anokfireball** [comment]
Any channels that mirror existing github repos (i.e. ```openPMD/openPMD-api```) will still require OAuth access, though.

> You cannot create a room with a same name that as an already existing repo. You may need to grant public/private repo scope on the GitHub org in order for us to see and auto-associate it (the repo should appear in the room name typeahead).

**Comment by ax3l** [comment]
I added an additional public API room and added oauth access as well.

Nevertheless, probably a single chat room is not too bad as an entry.

All rooms:
https://gitter.im/openPMD/home

**Comment by anokfireball** [comment]
I'll add a badge to the README that links to the gitter and then close the issue.

**Comment by anokfireball** [comment]
Closed in #291.
