### ISSUE TITLE
Record creation implies non-scalar RecordComponents

### ISSUE THREAD

**Issue by anokfireball** [openPMD/openPMD-api#287]
When creating a ```Record``` without supplying any ```RecordComponents```, ```Record::m_containsScalar``` is [default](https://github.com/openPMD/openPMD-api/blob/4832b11a91a70a9a6b7d91e119222fb02602b5ea/include/openPMD/backend/BaseRecord.hpp#L86)-initialized to ```false```. Under this assumption, an [empty group](https://github.com/openPMD/openPMD-api/blob/aca17f8563e53841b3bbb44a05a2a9e7cb3afb7d/src/Record.cpp#L60-L76) is created for such ```Record```s on ```Series::flush()```.

With major backends (e.g. [ADIOS](https://github.com/openPMD/openPMD-api/blob/dev/src/IO/ADIOS/CommonADIOS1IOHandler.cpp#L355-L367)) lacking node deletion entirely, this assumption is a design-flaw: The user can not at a later point resolve the ambiguity by specifying the ```RecordComponent``` as ```SCALAR```. This would lead to a [```std::runtime_error```](https://github.com/openPMD/openPMD-api/blob/dev/src/IO/ADIOS/CommonADIOS1IOHandler.cpp#L359) as the empty group can not reliably be replaced with a dataset.

To solve this, we should not make assumptions about (non-)scalar components. This means that we must not flush ```Record```s that contain no ```RecordComponents```. There are two options for reporting this to the user:
 - (preferred) ```throw``` when a ```Series::flush()``` reaches an empty ```Record```
 - (not preferred) skip the ```Record```; only create a dataset or group when the ambiguity is removed. When there is no such ```RecordComponent``` on file closing, this will silently discard the ```Record```.

**Comment by ax3l** [comment]
I think the first option is good.

Do you think that might be an issue in interactive workflows where a user decides half-way to throw away a record (e.g. typo) and go for another? Looks like option two or an explicit delete would be useful there. Can't we just delete (unflushed) records, even in ADIOS?

**Comment by anokfireball** [comment]
An option to delete nodes is already present for most objects with [```Container::erase()```](https://github.com/openPMD/openPMD-api/blob/dev/include/openPMD/backend/Container.hpp#L191-L212) and for attributes with [```Attributable::deleteAttribute()```](https://github.com/openPMD/openPMD-api/blob/de275058901fa1012e7b56a580660fe7e6d5fdae/include/openPMD/backend/Attributable.hpp#L106-L111). As long as the data only persists logically in this library (and not in a persistent form), the issue is trivial and entirely independent from the backend.

The situation outlined in this issue is unavoidable, though. Once a premature call to ```Series::flush()``` creates groups and/or datasets on disk, there is no reliable way (across backends) to recover into the desired state by modifying file structure... The key takeaway here is to use ```Series::flush()``` scarcely and deliberately once the desired structure is created.
