### ISSUE TITLE
Name sanitization bug during dataset creation

### ISSUE THREAD

**Issue by franzpoeschel** [openPMD/openPMD-api#310]
In [`src/IO/ADIOS/CommonADIOS1IOHandler.cpp`,](https://github.com/openPMD/openPMD-api/blob/dev/src/IO/ADIOS/CommonADIOS1IOHandler.cpp) the function `CommonADIOS1IOHandlerImpl::createDataset` sanitizes the dataset's name:
```c++
/* Sanitize name */
std::string name = parameters.name;
if( auxiliary::starts_with(name, '/') )
    name = auxiliary::replace_first(name, "/", "");
if( auxiliary::ends_with(name, '/') )
    name = auxiliary::replace_first(name, "/", "");
```
The second call to `auxiliary::replace_first` is likely intended to be `auxiliary::replace_last` instead in order to actually replace the slash at the _end_ of the name that has just been found.

**Comment by anokfireball** [comment]
Hi! You're probably the student that @ax3l told me about?

Thanks for reporting this bug. Yes, it is actually a bug.
Your assuption about ```auxiliary::replace_last``` is correct: Any path ```/foo/bar/``` should be sanitized to ```foo/bar```.

Do you want to fix this by yourself and create a pull request? I'd be happy to assist you at all times.

**Comment by franzpoeschel** [comment]
Hi, yep that's me. Thanks for your reply! – I've created a pull request with the fix.

**Comment by anokfireball** [comment]
The same bug is also present in the [HDF5 backend](https://github.com/openPMD/openPMD-api/blob/0.3.1-alpha/src/IO/HDF5/HDF5IOHandler.cpp#L198-L203).
