### ISSUE TITLE
Unify auxiliary::Variant and Attribute

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#340]
I think it makes sense to tell our `auxiliary::Variant` and the allowed types for it, aka `Attribute`, so we can implement the logic of `getCast< > ()` inside `auxiliary::Variant::get< >()` directly.

https://github.com/openPMD/openPMD-api/pull/337#discussion_r216566489

**Comment by anokfireball** [comment]
Dupe of #335.
