### ISSUE TITLE
CMake target: openPMD

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#38]
We currently build two "library" targets, core and io.

We should add a general "openPMD" target (with associated `libopenPMD.[a|so]`) so we do not confuse people.

**Comment by anokfireball** [comment]
The split into IO and core libraries was primairly aimed at speeding up compile times. Adding a union version that includes both should be effortless yet simplify usage.

Shall we include three library targets (IO, core, combined) or just the combined target? If you consider the user's perspective, a single one should suffice. From a developer's perspective, it would be beneficial to have all three components during debug/development.

**Comment by ax3l** [comment]
The splitting makes absolute sense and is fine!

Nevertheless, be aware that CMake/Make parallelizes compiles over translation units, not CMake targets. So besides the linking step, it makes no real difference.

If you like I can adjust the CMake and then create one final target that is installed only.

**Comment by ax3l** [comment]
I tried adding an intermedia `OBJECT` library but that makes linking dependencies a bit stupid because I can't add it there but only directly in the final target.

If you don't mind, I will therefore reduce the install just to one target for the C++ lib, also requiring only one link step.
