### ISSUE TITLE
MPI_INFO_ENV

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#44]
Currently the parallel test fails due to a missing `MPI_INFO_ENV` in `mpi.h`.

Please be aware this is an MPI 3.0+ feature:
  https://www.open-mpi.org/doc/v2.0/man3/MPI_Info_env.3.php

While requesting MPI 2.3+ support is very common, MPI 3+ is not necessarily yet common (standard: 2012) but might be acceptable nowadays. This just means our OpenMPI/MPICH/... dependencies need to be "quite recent" (in HPC terms).

Affects issues in:
- `src/IO/HDF5/ParallelHDF5IOHandler.cpp`

**Comment by anokfireball** [comment]
This was merely a exploratory test of what we could do with the new MPI_INFO. I abondoned it since it does not provide information useful to an already communicator-aware HDF5 backend. It being MPI3+ does not make it any more appealing.
