### ISSUE TITLE
MPI: storeChunk multiple times or not at all?

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-api#494]
In standard MPI domain decomposition, each MPI rank owns one rectangular chunk of the mesh. In this case, with `openPMD-api`, each MPI rank calls `storeChunk` once (from my understanding of [this (very nice and useful) example](https://openpmd-api.readthedocs.io/en/0.7.1-alpha/usage/parallel.html))

However, in some codes (e.g. AMReX-based), each MPI rank owns several rectangular chunks of the mesh (these chunks are non-overlapping, but may correspond to non-contiguous parts of the grid). Some MPI ranks may even have 0 chunk (rare, but possible).

In this case, it seems to me that each MPI ranks would have to call `storeChunk` several times (not necessarily the same number of times for each MPI rank), with different `local_data`, `chunk_offset`, `chunk_extent` each time. 

Is that supported by `openPMD-api`? Would it cause any bug if a user tries to use `storeChunk` in this way? In that case, should that user call `series.flush` after each call to `storeChunk`?

Thanks in advance!

**Comment by ax3l** [comment]
Yes, that's fully supported.

We have such use cases as well in PIConGPU, e.g. for particles: some ranks have zero particles and contribute nothing, others have 5 species which are written one by one.
(PIConGPU does not use the new API yet, but it's predecessor libSplash and ADIOS1. @franzpoeschel will upgrade PIConGPU in the upcoming months during his Master's thesis.)

> In that case, should that user call series.flush after each call to storeChunk?

This is only necessary if you want to operate "early" again on the passed memory. In PIConGPU for example, we need the host-side memory again after each species is dumped for the next species. Calling `Series::flush()` just guarantees you, that the memory exchanged with openPMD-api via `storeChunk`/`loadChunk` is now "yours" again to modify, free, etc.

You can just `storeChunk` all your data chunks one after another without `flush`ing. You just have to make sure that the memory you told openPMD-api to use in `storeChunk` is unchanged and not freed until you flush.

If you don't `Series::flush()` at all, we will do it on `Series`'s destruction. Also in this case, we will access the memory registered in `storeChunk`, so keep it alive and unchanged until then. In most cases, I would `flush` explicitly to make it more obvious when it happens and avoid thinking about destruction order of objects.

**Comment by RemiLehe** [comment]
Thanks for the detailed answer. This is very clear now.
