### ISSUE TITLE
C++ example with parallel write of 2D/3D mesh

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-api#495]
Right now, the documentation contains an example for parallel write in C++, but only with a 1d array and one element per MPI rank.

Would it be possible to add an example (or transform the current example) to include writing of 2D/3D mesh in parallel?

Thanks!

**Comment by ax3l** [comment]
I think it's best to update the `5_write_parallel` example. 1D chunking of a 1D mesh is too trivial of an example indeed.

**Comment by ax3l** [comment]
@RemiLehe I enhanced the example in #496. Feedback welcome! :)
