### ISSUE TITLE
Add option to install dynamic library?

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-api#503]
Would it make sense to add an option to install openPMD-api as a dynamic library? (instead of a static library)

The main use case would be using openPMD-api in a REPL setting, with `cling`. 
My understanding is that `cling` can only load dynamic libraries.

**Comment by ax3l** [comment]
Hi Rémi,


you can install dynamic libraries just by passing `-DBUILD_SHARED_LIBS=ON` to the `cmake` call. In CMake, the default for libraries is just `static` so I didn't change it and expose it with the typical control flags.

https://openpmd-api.readthedocs.io/en/0.8.0-alpha/dev/buildoptions.html#shared-or-static

Please note that you can either build a shared or a static lib at a time.

I will add a `+shared` variant to spack as well:
  https://github.com/spack/spack/pull/10847

I will probably change the default to `shared` in CMake itself for all install methods ([this way](https://github.com/ornladios/ADIOS2/blob/v2.3.1/CMakeLists.txt#L96-L106)).

>  My understanding is that `cling` can only load dynamic libraries.

Yes, for a JIT shared linking is the most logical and in cling the supported way: https://root-forum.cern.ch/t/jit-and-libraries/20309/11

**Comment by RemiLehe** [comment]
Great that there is the option `-DBUILD_SHARED_LIBS=ON`!
Sorry that I missed it!

**Comment by ax3l** [comment]
No problem, I will probably change the default to shared in the future as well (so one has to explicitly request static libs with `-DBUILD_SHARED_LIBS=OFF`).
Noted in #505

**Comment by ax3l** [comment]
I also updated the conda-forge recipe, so that it will install shared libraries by default as well: https://github.com/conda-forge/openpmd-api-feedstock/pull/25

In case the PR works, this will take some hours to land.
