### ISSUE TITLE
ADIOS1 deferred file creation

### ISSUE THREAD

**Issue by franzpoeschel** [openPMD/openPMD-api#520]
**Describe the bug**
The ADIOS1 backend [defers the creation of new files](https://github.com/openPMD/openPMD-api/blob/dev/src/IO/ADIOS/CommonADIOS1IOHandler.cpp#L376) to [the point where actual data is written](https://github.com/openPMD/openPMD-api/blob/dev/src/IO/ADIOS/CommonADIOS1IOHandler.cpp#L759).
It is possible to create workflows where between file creation and writing the first dataset, the backend will receive a OPEN_FILE IO task. The ADIOS1 backend will open the file [in read mode](https://github.com/openPMD/openPMD-api/blob/5b9eef397d66d652427df6704995c1b3d9e7a834/src/IO/ADIOS/CommonADIOS1IOHandler.cpp#L525). This will only succeed if the file exists not only logically, but also physically.

**To Reproduce**
Use the [sample C++ writing example](https://openpmd-api.readthedocs.io/en/latest/usage/serial.html#writing), but replace
```cpp
    Series series = Series(
        "../samples/3_write_serial.h5",
        AccessType::CREATE
    );
    cout << "Created an empty " << series.iterationEncoding() << " Series\n";

    MeshRecordComponent rho =
      series
          .iterations[1]
          .meshes["rho"][MeshRecordComponent::SCALAR];
```
… with …
```cpp
    Series series = Series(
        "3_write_serial%T.bp", // file-based layout, ADIOS1 backend
        AccessType::CREATE
    );
    cout << "Created an empty " << series.iterationEncoding() << " Series\n";
    series.iterations[1].setTime(0.5); // create file for iteration logically, but not physically
    series.iterations[0].setTime(0.5); // switch to other file to trigger an OPEN_FILE for switching back again

    MeshRecordComponent rho =
      series
          .iterations[1]
          .meshes["rho"][MeshRecordComponent::SCALAR];
```

**Expected behavior**
OPEN_FILE should succeed also with files that have been created logically only, but not physically.

**Comment by ax3l** [comment]
With #524 solved for HDF5, is this ADIOS1 issue still open/reproducible?

**Comment by franzpoeschel** [comment]
I tested it out, the above example finishes cleanly and the workaround in PIConGPU's openPMD plugin is apparently not necessary any longer either. Looks good.

**Comment by ax3l** [comment]
Nice, thanks to @guj for helping tremendously with the fixes!
