### ISSUE TITLE
import error on Mac OS 10.12.6 with anaconda3

### ISSUE THREAD

**Issue by JunCEEE** [openPMD/openPMD-api#559]
Hi,  this is not an urgent problem. Just happened to find the import on Mac OS 10.12.6 with anaconda3 is not successful. The following is the error when I tried import openpmd_api in python after installing it with this command `conda install -c conda-forge openpmd-api`.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-40d6f744b644> in <module>
      6 License: LGPLv3+
      7 """
----> 8 import openpmd_api
      9 
     10 if __name__ == "__main__":

ImportError: dlopen(/anaconda3/lib/python3.7/site-packages/openpmd_api.cpython-37m-darwin.so, 2): Symbol not found: __ZN7openPMD23ParallelADIOS1IOHandlerC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_10AccessTypeEP19ompi_communicator_t
  Referenced from: /anaconda3/lib/python3.7/site-packages/openpmd_api.cpython-37m-darwin.so
  Expected in: /anaconda3/lib/libopenPMD.ADIOS1.Parallel.dylib
 in /anaconda3/lib/python3.7/site-packages/openpmd_api.cpython-37m-darwin.so
```

**Comment by ax3l** [comment]
Thanks for the report! What is `conda list` outputting for you? Looks a bit like the OpenMPI variant was installed... interesting...

As far as I am aware, conda-forge only supports [MacOS 10.13 or newer](https://github.com/conda-forge/mpi4py-feedstock/issues/23#issuecomment-523149549). Is updating your OS an option?

Alternatively, try uninstalling the conda package and install via `pip`? This should build the package for you within the current active environment (of conda).

**Comment by JunCEEE** [comment]
Just created an entirely new conda environment with conda-forge and strict channel policy. It works now. It just seemed that my previous base environment was just too messy.

I'm still keeping Mac OS 10.12.6, no problems so far. Thanks.

**Comment by ax3l** [comment]
Awesome, thank you for the feedback! If you encounter any install problems again in the future, do not hesitate to open an issue again :)
