### ISSUE TITLE
Allow 2D/nested list in iteration.set_attribute function

### ISSUE THREAD

**Issue by JunCEEE** [openPMD/openPMD-api#561]
**Is your feature request related to a problem? If so, please describe.**
I tried to add an attribute with a 2D list to an iteration like this:

openPMD version: 0.9.0a
Python:
```python
import openpmd_api

series = api.Series(
    "dataMD.h5",
    api.Access_Type.create)
curStep = series.iterations[0]
curStep.set_attribute("boxEdge",[[1,0,0],[0,1,0],[0,0,1]])
```
but got this error:
```
TypeError: set_attribute(): incompatible function arguments. The following argument types are supported:
    1. (self: openpmd_api.Attributable, arg0: str, arg1: buffer) -> bool
    2. (self: openpmd_api.Attributable, arg0: str, arg1: bool) -> bool
    3. (self: openpmd_api.Attributable, arg0: str, arg1: int) -> bool
    4. (self: openpmd_api.Attributable, arg0: str, arg1: int) -> bool
    5. (self: openpmd_api.Attributable, arg0: str, arg1: float) -> bool
    6. (self: openpmd_api.Attributable, arg0: str, arg1: str) -> bool
    7. (self: openpmd_api.Attributable, arg0: str, arg1: List[int]) -> bool
    8. (self: openpmd_api.Attributable, arg0: str, arg1: List[int]) -> bool
    9. (self: openpmd_api.Attributable, arg0: str, arg1: List[float]) -> bool
    10. (self: openpmd_api.Attributable, arg0: str, arg1: List[str]) -> bool

Invoked with: <openPMD.Iteration of at t = '0.000000 s'>, 'boxEdge', [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
``` 

**Describe the solution you'd like**
Maybe support one more type?
`(self: openpmd_api.Attributable, arg0: str, arg1: List[List[]])`

**Additional context**
This problem is related to [this comment](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2966#issuecomment-531259748). We tried to compromise, and put the `box` information into the attribute of the iteration like [this](https://github.com/ejcjason/MDDomainExtension#data-structure-compromised). However, it seems not successful when we tried to put `boxEdge` attribute.

**Comment by ax3l** [comment]
Thanks for the report, this sounds useful indeed.
I am afraid not all data formats support nested arrays of arrays on the low-level, e.g. `ADIOS`' `.bp` format only supports fundamental types and arrays of fundamental types in attributes last time I checked. Seams to be still the same in ADIOS2 [[ref]](https://adios2.readthedocs.io/en/latest/api_high/api_high.html#_CPPv4I0EN6adios27fstream15write_attributeEvRKNSt6stringERK1TRKNSt6stringEKNSt6stringEKb).

Is it potentially possible to either:
- flatten this into a 1D array `[1,0,0, 0,1,0, 0,0,1]` or
- encode this into a mask, e.g. of simple base 10 `[100, 010, 001]` or
- introduce a naming scheme for each sub list, such as `boxEdge_x`, `boxEdge_y`, ...?

**Comment by JunCEEE** [comment]
Thanks. They are very good suggestions. In this case, I would choose to fatten the array. Maybe it's better to put this kind of nested arrays as a dataset?

**Comment by ax3l** [comment]
Great that this works for you! Don't worry, the array is still very short and very much "meta data". As a rule of thumb, everything below a few dozen kByte is a good candidate for an attribute (e.g. from what [HDF5](https://support.hdfgroup.org/HDF5/doc/Advanced/MetadataCache/index.html) does).

**Comment by ax3l** [comment]
Probably the question is answered with this. If not, please feel free to comment or open a new issue for further questions :)
