### ISSUE TITLE
No configuration file for nlohmann_json 3.7.0

### ISSUE THREAD

**Issue by abonatto** [openPMD/openPMD-api#562]
Dear developers,

I am trying to install openpmd-api using spack,

```
spack install openpmd-api
```

However, I am experiencing the the following problem:

```
==> Error: ProcessError: Command exited with status 1:
    'cmake' '/usr/local/bin/spack/...

1 error found in build log:
     14    -- Detecting CXX compiler ABI info - done
     15    -- Detecting CXX compile features
     16    -- Detecting CXX compile features - done
     17    -- Found MPI_C: /usr/local/bin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.3-bhtxi3rm2tuwmytfsp32opbjucqkngh6/lib/libmpi.so (found versi
           on "3.1")
     18    -- Found MPI_CXX: /usr/local/bin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.3-bhtxi3rm2tuwmytfsp32opbjucqkngh6/lib/libmpi_cxx.so (found
            version "3.1")
     19    -- Found MPI: TRUE (found version "3.1")
  >> 20    CMake Error at CMakeLists.txt:140 (find_package):
     21      Could not find a configuration file for package "nlohmann_json" that is
     22      compatible with requested version "3.7.0".
     23    
     24      The following configuration files were considered but not accepted:
     25    
     26        /usr/local/bin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/nlohmann-json-3.5.0-quxabe22xxuqokpgbg2acc2prpfi5pap/lib/cmake/nlohmann_json/nlohmann
           _jsonConfig.cmake, version: 3.5.0
```

Do you have any suggestion about how to fix it?

Regards.

Alex

**System environment**
 - operating system: Ubuntu 18.04.3 LTS
 - machine: Intel Xeon Silver 4114
 - name and version of Python implementation: 3.7.3

**Comment by ax3l** [comment]
Thank you for the report!
Is it possible your source of `spack` itself is a bit outdated? Can you just update the spack sources you cloned?

I am currently installing straight form this repo's `dev` instead of fixed versions, which can lead to that behaviour. I'll start tagging release versions on spack soon, just did not do that yet since I changed it quite regularly in the past when we added new backends.

**Comment by abonatto** [comment]
Indeed, it worked using `dev` instead of `0.12.1`. Thanks.

**Comment by ax3l** [comment]
Great that this works! :)
