### ISSUE TITLE
Question: python parallel examples without `comm`?

### ISSUE THREAD

**Issue by LDAmorim** [openPMD/openPMD-api#590]
Hi,
I just started to use OpenPMD-api because it seems like a great API.
Tried to run the examples of reading/writing in parallel from the documentation [url](https://github.com/openPMD/openPMD-api/blob/dev/examples/4_read_parallel.py) in a jupyter notebook.
And I am not sure what I am doing wrong (I also didn't find a related issue open, but I might be misunderstanding this) so I decided to ask it here.
It seems to me that when creating `series`, the argument `comm` might not be necessary. With it I got the error below:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-7bfdc5766a5c> in <module>
     21         "../samples/git-sample/data%T.h5",
     22         openpmd_api.Access_Type.read_only,
---> 23         comm
     24     )
     25     if 0 == comm.rank:

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. openpmd_api.Series(filepath: str, access_type: openpmd_api.Access_Type)

Invoked with: '../samples/git-sample/data%T.h5', Access_Type.read_only, <mpi4py.MPI.Intracomm object at 0x1045bfc70>
```
Without `comm` I could create the `.h5` file. But it seemed to be  giving me a strange result when reading with the other example file:
```
Read a series in parallel with 1 MPI ranks
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-28-5a8db3e5adb3> in <module>
     11               comm.size))
     12 
---> 13     E_x = series.iterations[100].meshes["E"]["x"]
     14 
     15     chunk_offset = [comm.rank + 1, 1, 1]

IndexError: Key '100' does not exist (read-only).
```

The same happens if I try iteration nr 9 instead of 100.
The file seems to be created well because the code:
``` python
import h5py
path_file = './5_parallel_write_py.h5'
fin=h5py.File(path_file,'r')
datasets=list(fin.keys())
print(datasets)
print(fin[datasets[0]].keys())
print(fin[datasets[0]]['1'].keys())
print(fin[datasets[0]]['1']['meshes'].keys())
print(fin[datasets[0]]['1']['meshes']['mymesh'][9])
fin.close()
```
Gives what seems to me to be the right result:
```
['data']
<KeysViewHDF5 ['1']>
<KeysViewHDF5 ['meshes']>
<KeysViewHDF5 ['mymesh']>
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
```

I will now try to understand how `series` is implemented, but thought I should ask you first:
1) do you know what I am doing wrong?
2) is `comm` supposed to be used in `series` and the issue is with my installation?
3) do you have any suggestion on how I can read the file?

Thanks for your help,
Diana

**Environment**
- MacOS High Sierra
- clang 10.0.0
- python 3.7.3
- jupyter-notebook 6.0.1
- numpy 1.17.3
- mpi4py 3.0.3
 - version of openPMD-api: 0.8.0-alpha
 - installed openPMD-api via: conda-forge

**Comment by ax3l** [comment]
Thank you for the excellent question and details!

This looks to me like you are trying to use the MPI-parallel version of openPMD-api, but only the serial version is installed (the constructor only knows the serial number of arguments without `comm`).

If you print
```py
import openpmd_api                                                      

print(openpmd_api.variants)
```
it will probably show something like
```py
{'adios1': True, 'adios2': False, 'hdf5': True, 'json': True, 'mpi': False}
```

Since you installed via conda, just [run the following](https://github.com/openPMD/openPMD-api#conda) in your environment to get the MPI enabled package instead:
```bash
conda uninstall openpmd-api
conda install -c conda-forge openpmd-api=*=mpi_mpich*
```

That said, I think you do not need to use the MPI-parallel version for writing right now, or do you? You can just follow the [serial read example](https://openpmd-api.readthedocs.io/en/0.9.0-alpha/usage/serial.html#python) instead.

To answer the question in the subject
> python parallel examples without `comm`?

If you want to use (MPI-) parallel examples you need MPI support in the library as well (see install instructions above). As soon as `print(openpmd_api.variants)` shows `'mpi': True` you can pass the MPI communicator `comm` into `Series` :)

**Comment by ax3l** [comment]
> But it seemed to be giving me a strange result when reading with the other example file:
> ...
> ---> 13     E_x = series.iterations[100].meshes["E"]["x"]
> ...
> IndexError: Key '100' does not exist (read-only).

This error just says you try to read iteration 100 but iteration 100 does not exist in the file you are reading (index key 100 does not exist in the `series.iterations` object).

Try to list
```py
print(list(series.iterations))
```
to see what's available inside :)
