### ISSUE TITLE
Documentation on unitSI and unitDimension

### ISSUE THREAD

**Issue by LDAmorim** [openPMD/openPMD-api#591]
Hi,
I am new to OpenPMD and I really appreciate your documentation.
But I found it challenging to understand the meaning of the documentation `units` section under `FirstWrite`:
```python
# conversion to SI
B_x.set_unit_SI(1.e-4)
B_y.set_unit_SI(1.e-4)
B_z.set_unit_SI(1.e-4)

# unit system agnostic dimension
B.set_unit_dimension({
    api.Unit_Dimension.M:  1,
    api.Unit_Dimension.I: -1,
    api.Unit_Dimension.T: -2
})
```
Because I didn't relate automatically M to mass, I to current and T to time.

It is probably just due to my ignorance, that I did not associate dimensionality with those labels right away.

But, just in case any one else asks about this, I thought it could be useful to open this issue for them to find.

Of course, please feel free to dismiss or delete this if you disagree with what I wrote.

Thanks,
Diana

**Comment by ax3l** [comment]
Thank you very much for the feedback, I really appreciate it.

I added more documentation on the labels in #592, I would love your thoughts on the pull request. Please feel free to annotate therein :)
