### ISSUE TITLE
Compile time warnings with 0.13.0-dev

### ISSUE THREAD

**Issue by pordyna** [openPMD/openPMD-api#651]
Compiling a project with `openPMD `results in a bunch of compile-warnings, mostly "statement is unreachable". I get those warnings when I compile a new [`PIConGPU`](https://github.com/ComputationalRadiationPhysics/picongpu) example added in this [PIConGPU PR. ](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3134)

**Expected behavior**
These warnings are probably not relevant and shouldn't appear in the compile log.

**Software Environment**
 - version of openPMD-api: 0.10.0-dev
 - installed openPMD-api via:  from source
 - machine: hemera
 - gcc: 7.3.0
 - cmake: 3.15.2

All related warnings begin, in the atatched log file, with `/home/ordyna35/bin/openPMD/include/openPMD`.
[compileLogOpenPmdWarnings.log](https://github.com/openPMD/openPMD-api/files/4040382/compileLogOpenPmdWarnings.log)

**Comment by ax3l** [comment]
Hi,

Thanks for the report!
Can you please try again with openPMD-api 0.13.0 (update: or even better the current `dev`) and see if you still get those warnings?

The only warning I am currently aware of is #648 with GCC+NVCC.

**Comment by pordyna** [comment]
Hi :)
I tried compiling with 0.13.0 and the current dev  today and I still get the warnings. 
The new compile-log( api from the current `dev` ):  [compileLogOpenPmdWarnings-new-dev.log](https://github.com/openPMD/openPMD-api/files/4071380/compileLogOpenPmdWarnings-new-dev.log)

**Comment by ax3l** [comment]
Thanks, there seam to be some unreachable code warnings left that did not pop up in other applications on include. Will update accordingly, thanks! :)

**Comment by ax3l** [comment]
Okay, #659 should address these warnings.
Can you please update your openPMD-api `dev` branch, build and check if there are any warnings from it left when compiling with PIConGPU?

**Comment by ax3l** [comment]
ping @pordyna: are there any warnings from openPMD-api left for you after the latest updates on `dev`?

**Comment by pordyna** [comment]
Thanks @ax3l, for fixing it so quickly.  The warnings are gone now :smile: :rocket:

**Comment by ax3l** [comment]
Hooray, thank you for testing!
Will put out a new tagged version release soon that you can then rely on.
