### ISSUE TITLE
Backend- and dataset-specific configuration (e.g. compression)

### ISSUE THREAD

**Issue by franzpoeschel** [openPMD/openPMD-api#688]
Related: [backend-specific configuration via JSON](https://github.com/openPMD/openPMD-api/pull/569) and [passing of advanced backend parameters](https://github.com/openPMD/openPMD-api/issues/150).

In issue #150, @C0nsultant proposes to implement backend-specific configuration in two places: for `openPMD::Series` and `openPMD::Dataset`. So far, PR #569 implements backend-specific configuration for `openPMD::Series`:
```cpp
    Series(
        std::string const & filepath,
        AccessType at,
        std::string const & options = "{}" );
```
…, but not for `openPMD::Dataset`. This class, however, has two fields, that control a backend-dependent configuration of compression and transformation:
```cpp
class Dataset
{
    // ...
public:
    Dataset(Datatype, Extent);

    //...

    std::string compression;
    std::string transform;
};
```

The HDF5 backend implements neither of these, the ADIOS1 backend implements transform, the ADIOS2 backend implements compression.

After an offline discussion with @psychocoderHPC, we have come up with the following proposal: The fields `compression` and `transform` are deprecated/removed from the API (which should hopefully not be a huge issue due to the very incomplete implementation status, as mentioned above) and replaced through a JSON-formatted string with the exact same structure as for `openPMD::Series`. This would then  separate backend-specific configuration more clearly.

Backends should behave such that all configuration options can be set globally in the `openPMD::Series` configuration, but dataset-specific options (including `compression` and `transform`) can be overridden on a per-dataset level.

Some options do not make sense to be overriden on a per-dataset level, such as the chosen engine in ADIOS2 (e.g. file engines or streaming engines). The [`TracingJSON`](https://github.com/openPMD/openPMD-api/blob/938b6722c05c985598d354c43eda1a492dfae8de/include/openPMD/auxiliary/JSON.hpp) helper class may prove helpful to issue a warning if such an option has been specified for a dataset.

Example for ADIOS2, global configuration (in `openPMD::Series`):
```
{
  "adios2": {
    "engine": {
      "type": "sst",
      "parameters": ["BufferGrowthFactor": "2.0", "QueueLimit": "2"]
    },
    "dataset": {
      "compression": "bzip2"
    }
  }
}
```
…which may be overridden by a dataset-specific configuration:
```
{
  "adios2": {
    "dataset": {
      "compression": "sz"
    }
  }
}
```

**Comment by ax3l** [comment]
perfect, would do it the same way. (this is somewhat similar to unix config file logic, which I like.)
