### ISSUE TITLE
No verbose output whether openPMD-api was found or not via CMake

### ISSUE THREAD

**Issue by PrometheusPi** [openPMD/openPMD-api#761]
When including openPMD-api in a project compiled using CMake, the fact whether openPMD-api was found or not during linking/compiling is not communicated verbosely. 

This could be solved by the host code adding CMake messages manually as done in [this pull request](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3281), but it would be more convenient if openPMD-api could provide such output on its own as e.g. ADIOS does.

**Comment by ax3l** [comment]
We use ADIOS1 in PIConGPU with a self-written, old find-module that does such verbose output.

With modern CMake packages and especially the config-module that is being used, It is indeed the right thing to add the extra output depending on the `openPMD_FOUND` variable as you did these days.

**Comment by PrometheusPi** [comment]
@ax3l Thanks for your feedback. With the information that the user need to implement the output, the issue can be closed, do you agree?

**Comment by ax3l** [comment]
Thanks, yes I agree. Thank you for raising the question!
