### ISSUE TITLE
Rename Variadic to Variant

### ISSUE THREAD

**Issue by anokfireball** [openPMD/openPMD-api#78]
The generic storage used for e.g. Attribute values was initially designed to store arbitrary datatypes, hence the name ```Variadic``` was chosen.

During developement it became pretty obvious that a restriction to a finite, predefined set of datatypes is the more sensible way. Since ```boost```/```mpark```/```std``` ```variant```s do exactly that, they have been used all along.

I propose to rename the auxiliary class [Variadic](https://github.com/openPMD/openPMD-api/blob/cdc773ffb785f9428b46b7bcf7e89fc1a3e9116b/include/auxiliary/Variadic.hpp) to ```Variant``` to reflect this decision.

**Comment by ax3l** [comment]
Agreed!
