### ISSUE TITLE
ADIOS2: closed attribute read warning

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#784]
**Describe the bug**
Reading back ADIOS2 data, I see warnings of the type:
```
[ADIOS2] Warning: Attribute with name __is_boolean__/data/0/closed has no type in backend.
[ADIOS2] Warning: Attribute with name __is_boolean__/data/100/closed has no type in backend.
[ADIOS2] Warning: Attribute with name __is_boolean__/data/500/closed has no type in backend.
[ADIOS2] Warning: Attribute with name __is_boolean__/data/300/closed has no type in backend.
[ADIOS2] Warning: Attribute with name __is_boolean__/data/200/closed has no type in backend.
[ADIOS2] Warning: Attribute with name __is_boolean__/data/400/closed has no type in backend.
```

in my logs.

**To Reproduce**

Read-back of an ADIOS2 BP4 file that closed iterations with `::close()` during write.

**Expected behavior**

Maybe we can use an attribute type that we can re-identify easily (`int`) or fix read-back of our self-made `bool` types in ADIOS2? 

**Software Environment**
 - version of openPMD-api: 0.12.0
 - installed openPMD-api via: conda-forge
 - operating system: Ubuntu 18.04 (64bit) on x86
 - machine: my laptop
 - name and version of Python implementation: CPython 3.8.5
 - version of HDF5: 1.10.6
 - version of ADIOS1: 1.13.1
 - version of ADIOS2: 2.6.0
 - name and version of MPI: w/o MPI

**Additional context**

Saw this while trying to read-back ZFP compressed data sets.

**Comment by franzpoeschel** [comment]
Ah, I already fixed that same issue a while ago on my streaming branch, I can cherry-pick the commit quickly.
