### ISSUE TITLE
Python garbage collection: store_chunk does not keep data alive

### ISSUE THREAD

**Issue by franzpoeschel** [openPMD/openPMD-api#833]
Garbage collection in the Python API will not keep alive datasets inserted into `Record_Component.store_chunk()`.

**To Reproduce**
```python
import numpy as np
import openpmd_api as io

dtype = np.dtype('float')
extent = 1000

def write_good():
    series = io.Series("sample_good.bp", io.Access_Type.create)
    E_x = series.iterations[0].meshes["E"]["x"]
    E_x.reset_dataset(io.Dataset(dtype, [extent]))
    data = np.zeros(extent, dtype=dtype)     # variable `data` will keep the dataset alive
    E_x.store_chunk(data, [0], [extent])
    series.flush()

def write_bad():
    series = io.Series("sample_bad.bp", io.Access_Type.create)
    E_x = series.iterations[0].meshes["E"]["x"]
    E_x.reset_dataset(io.Dataset(dtype, [extent]))
    E_x.store_chunk(np.zeros(extent, dtype=dtype), [0], [extent])     # no variable to keep the dataset alive
    series.flush()

write_bad()
write_good()

```
Results:
```
> bpls sample_bad.bp/ -d | head -n 10
  double   /data/0/meshes/E/x  {1000}
    (  0)    0 4.65427e-310 4.65427e-310 4.65427e-310 0 8.74496e-322
    (  6)    6.91176e-310 4.65427e-310 0 0 4.65427e-310 4.94066e-323
    ( 12)    5.78208e+160 1.32113e-319 7.90505e-323 0 4.65427e-310 3.45846e-323
    ( 18)    8.74753e-308 0 0 0 0 0
    ( 24)    7.90505e-323 0 0 7.16395e-322 1.1363e-313 4.65427e-310
    ( 30)    4.94066e-323 5.78208e+160 1.32113e-319 7.90505e-323 4.65427e-310 3.45846e-323
    ( 36)    8.74753e-308 0 0 0 0 0
    ( 42)    7.90505e-323 0 0 2.42092e-322 4.65427e-310 4.65427e-310
    ( 48)    4.65427e-310 4.65427e-310 0 2.42092e-322 4.65427e-310 4.65427e-310

> bpls sample_good.bp/ -d | head -n 10
  double   /data/0/meshes/E/x  {1000}
    (  0)    0 0 0 0 0 0
    (  6)    0 0 0 0 0 0
    ( 12)    0 0 0 0 0 0
    ( 18)    0 0 0 0 0 0
    ( 24)    0 0 0 0 0 0
    ( 30)    0 0 0 0 0 0
    ( 36)    0 0 0 0 0 0
    ( 42)    0 0 0 0 0 0
    ( 48)    0 0 0 0 0 0
```
Garbage collection bugs being as unpredictable as they are, this bug may not be always triggered. For me, switching out the two function calls resulted in a usable dataset.

**Expected behavior**
Garbage collection should not claim a chunk as long as it is still needed in the backend.

**Software Environment**
 - version of openPMD-api: current dev, commit `8f153f487352b56837c69cc93048d31e14ab46b4`.
 - installed openPMD-api via: manually
 - operating system: Ubuntu 20.10
 - machine: own laptop
 - name and version of Python implementation: Conda-installed Python 3.8.3
 - version of ADIOS2: 2.6.0

**Additional information**
The reason for this error is relatively easily recognized by the use of `share_raw` in [here](https://github.com/openPMD/openPMD-api/blob/574269a39c75fa6844450876b3de957d457b0c73/src/binding/python/RecordComponent.cpp#L288). I'm not quite sure how to actually solve this, though.

The `.load_chunk` method shares the same issue from looking at the implementation, but it's probably less critical here since users will generally keep around the variable for later access anyway. But if we find a solution for `.store_chunk`, it's likely to be applicable for `.load_chunk` as well anyway.

**Comment by ax3l** [comment]
Good call and analysis.

Besides getting #484 the default to protect users, we should document this maybe as a counter-example.

After inquiring with pybind11 and Twitter about this (thanks @skuschel & @RemiLehe): One could check [sys.getrefcount](https://groverlab.org/hnbfpr/2017-06-22-fun-with-sys-getrefcount.html) ([ref](https://docs.python.org/3.8/library/sys.html#sys.getrefcount) / [PyObject equivalent](https://docs.python.org/3/c-api/structures.html#c.Py_REFCNT)) in the passed object. We could add a temporary object on ref-count 1 maybe 2. Draft in #912
