### ISSUE TITLE
source ID changes in parallel I/O test

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#867]
**Describe the bug**

On conda-forge, I see the following assert in ParallelIOTests:
```
$SRC_DIR/test/ParallelIOTest.cpp:346: FAILED:
  REQUIRE( chunk.offset == Offset{ static_cast< unsigned >( chunk.sourceID ), 0 } )

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ParallelIOTests is a Catch v2.6.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
available_chunks_test
-------------------------------------------------------------------------------
$SRC_DIR/test/ParallelIOTest.cpp:358
...............................................................................

$SRC_DIR/test/ParallelIOTest.cpp:346: FAILED:
  REQUIRE( chunk.offset == Offset{ static_cast< unsigned >( chunk.sourceID ), 0 } )
with expansion:
  { 0, 0 } == { 1, 0 }

with expansion:
  { 0, 0 } == { 1, 0 }
```

**To Reproduce**
This occurs on macOS with OpenMPI. MPICH is unaffected.

Just running the tests as usual with `ctest`.

See: https://github.com/conda-forge/openpmd-api-feedstock/pull/59

**Expected behavior**
Should not fail or not check an attribute that is runtime dependent.

**Software Environment**
 - version of openPMD-api: 0.13.0
 - installed openPMD-api via: conda-forge (curing release workflow)
 - operating system: macOS 10.15 with Clang 11.0.0 (from LLVM, not AppleClang)
 - machine: Azure Pipelines
 - name and version of Python implementation: CPython 3.9 (all affected)
 - version of HDF5: 1.10.6
 - version of ADIOS1: 1.13.1
 - version of ADIOS2: 2.6.0
 - name and version of MPI: OpenMPI 4.0.5

**Additional context**
Occurred during release of openPMD-api 0.13.0 on conda-forge.

**Comment by franzpoeschel** [comment]
Can you check whether #871 fixes this? @ax3l
