### ISSUE TITLE
loadChunk: std::future?

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#91]
We could `.loadChunk()` let return a `std::future` which would make it on "simple use" (not using the result val -> destroyed) a blocking operation and on extended use (using the future) a nice C++11-ish object.

Any comments?

The question is then still how to bind the *async* functionality to Python...

**Comment by anokfireball** [comment]
On first thought, I like the idea of spreading this invisible mechanism. Ideomatic async-on-demand is a really nice feature that could be integrated into more of our workflows.

_I assume_ you had something like this in mind:
```cpp
auto s = openPMD::Series::read("file.h5");
auto E_x = s.iterations[1].meshes["E"]["x"];

std::unique_ptr< double[] > chunk_data;
auto future = E_x.loadChunk({0}, {1}, chunk_data);
/* wörkwörk */
future.wait();
```
With that in mind, I think ```.loadChunk()``` is not a good place to apply it for two reasons:
- It would make the intended workflow less obvious.
Let me outline the relevant part of the API design for my reasoning:
All IO operations - whether implicit (e.g. ```.setAttribute()```) or explicit (e.g. ```.loadChunk()```) - are appended to an [```IOTask```-queue](https://github.com/openPMD/openPMD-api/blob/dev/include/openPMD/IO/AbstractIOHandler.hpp#L120). The queue is only drained / the tasks only executed when ```Series::flush()``` is called (potentially in the destructor). This design was chosen so the user does not have to think about the order in which operations occur - they mirror the order in the source code precisely.
For ```.loadChunk()``` to return a future, the queue would either have to be flushed (which results in the next bullet-point) or we would have to introduce mutlitple time-lines. Doing so will get messy and probably confusing:
 ```cpp
auto s = openPMD::Series::read("file.h5", 
                                AccessType::READ_WRITE /* !!! */);
auto E_x = s.iterations[1].meshes["E"]["x"];

E_x.setComment("There is now 1 IOTask in the queue");

std::shared_ptr< double > store_chunk;
/* fill store_chunk */
E.storeChunk({0}, {1},  store_chunk); // not async, it might require other IOTasks
                                       // currently in the queue (DSet create,...)
                                       // at least 2 IOTasks in queue now

std::unique_ptr< double[] > load_chunk;
auto future_load = E_x.loadChunk({0}, {1}, load_chunk); // new timeline, not in queue

E_x.setComment("There are now at least 3 IOTasks in the queue");
auto future_queue = s.flush();

future_load.wait();
future_queue.wait();

if( *store_chunk == *load_chunk )
  /* implement the proposal by waiting for queue to be empty */
  /* diverging paths were superflous */
else
  /* do not wait for queue to be empty */
  /* we now have user-made race conditions */
```

- It is superfluous.
The example in the assumption can be expressed already:
```cpp
auto s = openPMD::Series::read("file.h5");
auto E_x = s.iterations[1].meshes["E"]["x"];

s.flush(); // empty the queue completely

std::unique_ptr< double[] > chunk_data;
E_x.loadChunk({0}, {1}, chunk_data);
auto future = s.flush();
/* wörkwörk */
future.wait();
```

**Comment by ax3l** [comment]
> On first thought, I like the idea of spreading this invisible mechanism. Ideomatic async-on-demand is a really nice feature that could be integrated into more of our workflows.

The idea is actually from an implementation in another, still private, repo we are currently developing with @michaelsippel . We can fill you in offline for now - I think that would interest you as well and has some pretty neat concepts for larger integration. Anyway, it would operate on top of what we discuss here.

**Comment by ax3l** [comment]
back to topic: I don't see why the current concept should not allow to return a future which is only (as now) fullfilled if the latest IOtask (and all before it) are done? But for consistency, every operation you mention above should then return a future which can be messy in handling many objects (or very synchronous if directly destructed) as well. We probably need to think this further in case we would like to allow it.

I will keep this for the future, also makes the python bindings for now easier.

**Comment by ax3l** [comment]
Thx for the info, I think that answered my questions for now.
Please don't forget a *conceptual* documentation on the `IOTask-queue` in the manual #153
