### ISSUE TITLE
uint64_t should be used for all extents

### ISSUE THREAD

**Issue by psychocoderHPC** [openPMD/openPMD-api#95]
I am not sure if 32bit systems should be supported but if than uint64_t should be used for all extents instead of size_t. size_t is 32bit on 32bit systems and can result in issues with offsets or extents over 4GiB.
I saw in the code that offset and extent is defined as uint64_t but on many other places size_t is used.

**Comment by ax3l** [comment]
I think that issue is fixed now :)

The are still some minor warnings on 32bit Windows builds in `HDF5IOHandler.cpp` on attribute reads (`hsize_t` and `std::vector` storage) but they do not get over 4 GB.
