### ISSUE TITLE
CMake: variable not visible outside of the method scope

### ISSUE THREAD

**Issue by psychocoderHPC** [openPMD/openPMD-api#969]
**Describe the bug**

The lines https://github.com/openPMD/openPMD-api/blob/f5dc8e25fcc26b3e78857e7cd30b6056a4b9255c/CMakeLists.txt#L57-L61 will have no effect.  The variable `openPMD_HAVE_${name}` will only be visible within the method because the scope is missing.

**Comment by ax3l** [comment]
Oh that's right. Should be either a macro, a cached var, or set `PARENT_SCOPE`.
I wonder if I tried to set an existing cached var to a different value with it...
