### ISSUE TITLE
Simplify C++ code?

### ISSUE THREAD

**Issue by eschnett** [openPMD/openPMD-api#985]
I see that e.g. the file `Container.hpp` contains the two signatures
```
mapped_type& operator[](key_type const& key);
mapped_type& operator[](key_type&& key);
```
where the first copies and the second moves its argument if a new container entry is created.

I believe (please correct me if I am wrong) that this can be simplified to a single function
```
mapped_type& operator[](key_type key);
```
that always moves its argument.
- When this function is called with a `const&` argument, then the caller will make a copy. This function then moves the key. The overall cost is one copy, same as now.
- When this function is called with a `&&` argument, then the caller will move the argument. This function then moves the key again. The overall cost is zero copies, same as now.

**Comment by ax3l** [comment]
Thanks, great idea.

Re-visiting the interface of `std::map` on which that one is based, isn't the universal reference all we need?
https://en.cppreference.com/w/cpp/container/map/operator_at
```C++
mapped_type& operator[](key_type&& key);
```

By-value passing should also work if we `std::move` the argument inside, if I am not mistaken.

I quickly tried this (also removing the same signature from `BaseRecord`, and if we go with universal references then the following construct does not match the signature:
```C++
for( auto const& component : *pList.paths )
   (*this)[ component ]
```

**Comment by eschnett** [comment]
The signature you write only accepts rvalue references. You cannot call it with a const reference.

I was mistaken in my suggestion above. In the case where the key already exists, the current code makes no copy of the key. With my suggestion, it would make one. Please disregard.

**Comment by ax3l** [comment]
Ah right, shouldn't think value semantics after a day of meetings.
Just realized map exposes both signatures for the same reason and misread the cpp reference earlier.
