### ISSUE TITLE
Missing function `Mesh::unitDimension`

### ISSUE THREAD

**Issue by eschnett** [openPMD/openPMD-api#991]
There is no function `Mesh::unitDimension` that would return the unit dimension of a mesh. This counterpart to `setUnitDimension` seems to be missing.

**Comment by ax3l** [comment]
I think `Mesh` should have that function derived from `BaseRecord` :)
Just checked, we have coverage for that getter, e.g. here:
https://github.com/openPMD/openPMD-api/blob/3ee8b57dd8fa2d1559f5ee85ba08f5026db60be0/test/SerialIOTest.cpp#L1861-L1868

**Comment by eschnett** [comment]
It does. I just didn't find it. Sorry!
