### ISSUE TITLE
Should multiple variables be in the same `Mesh`?

### ISSUE THREAD

**Issue by eschnett** [openPMD/openPMD-api#992]
I have multiple grid functions (variables, fields) (e.g. lapse, shift, metric). The lapse is a scalar, the shift is a vector, and the metric is a symmetric tensor. They share the same discretization. They have 1, 3, and 6 components, respectively.

- Should they be stored on the same `Mesh`? The standard says these should be separate "mesh records".
- If so, is there a way to create "sub-records" or "groups" to separate the tensor components of these fields?

**Comment by ax3l** [comment]
In openPMD, we usually recommend to group in a record (mesh or particle record) the quantities that are of the same physics, i.e. components of the same `unitDimension`.

So if they have the same discretization but one is a scalar density field and the other a scalar charge density, we would not store the in the same `Mesh`.

We do a relatively flat naming right now to simplify reading:
- records are [a scalar, a vector, or a tensor](https://github.com/openPMD/openPMD-standard/blob/upcoming-2.0.0/STANDARD.md#scalar-vector-and-tensor-records)
- non-scalar records have record components
- record components are of the same "physical dimension" (e.g. all describe a length or all belong to an electric field)
- a record can be a mesh (ND field) or a particle (1D arrays, table/data frame)

There are at the moment no further sub-groups. Most encode something in a user-defined name or an additional attribute, if they want to store a relation between various meshes that is not able to be captured that way.

> They have 1, 3, and 6 components, respectively.

This sounds to me like 3 records, one is scalar, one a vector and one a tensor record.

**Comment by eschnett** [comment]
Thanks!
